.github/workflows/build-publish.yml

This is copied from https://github.com/Farama-Foundation/PettingZoo/blob/e230f4d80a5df3baf9bd905149f6d4e8ce22be31/.github/workflows/build-publish.yml
We may need to modify it

added experimental pypi build config file, copied from PettingZoo

---

CODE_OF_CONDUCT.rst

Update the Code of Conduct for Gymnasium

Update Code of Conduct

---

gymnasium/wrappers/normalize.py
requirements.txt
setup.py

Replace gym-notices in favor of gymnasium-notices

Update to gymnasium notices

---

README.md
gymnasium/envs/box2d/bipedal_walker.py
gymnasium/envs/box2d/car_racing.py
gymnasium/envs/classic_control/pendulum.py
gymnasium/envs/mujoco/mujoco_env.py
gymnasium/wrappers/pixel_observation.py
tests/envs/utils.py

Changes were made between v26 and v26.1, this PR makes all of the changes
See https://github.com/openai/gym/releases/tag/0.26.1 for release notes

Upstream v26.1 changes

---

docs/.gitignore
docs/environments/atari/complete_list.md
docs/scripts/gen_envs_display.py

Fix: [https://gymnasium.farama.org/environments/atari/complete_list/](https://gymnasium.farama.org/environments/atari/complete_list/)

Fix environments complete list

---

docs/content/basic_usage.md
docs/content/environment_creation.md
docs/content/handling_timelimits.md
docs/content/vectorising.md
docs/environments/atari.md
docs/environments/box2d.md
docs/environments/classic_control.md
docs/environments/mujoco.md
docs/environments/third_party_environments.md
gymnasium/core.py

Fix the environments' page syntax and especially grammar

Fix environments' page syntax

---

README.md

This allows for better analytics

Change discord invite link to be different from gym

---

docs/content/gym_compatibility.md
docs/index.md

This PR adds a page for compatibility with Gym noting the three methods that Gymnasium provides compatibility.

Add Gym compatibility blog

---

README.md

We add TorchRL to the notable related libraries in README.md.

Add TorchRL to the Notable Related Libraries in README.md

---

.github/workflows/build-docs.yml
.github/workflows/docs-manual-versioning.yml
.github/workflows/docs-versioning.yml
docs/conf.py
docs/index.md

* Add documentation site versioning

Docs Versioning

---

docs/scripts/gen_mds.py

* Add missing space
* Display only one `inf` for mujoco environemnts

Small improvements to environments pages

---

docs/content/migration-guide.md

DOC v21 to v26 Migration Guide, typo fixes

---

gymnasium/utils/passive_env_checker.py
tests/envs/test_gym_conversion.py
tests/utils/test_passive_env_checker.py

This PR improves the warnings reported by the environment checker

Improves the error by environment checker

---

gymnasium/vector/sync_vector_env.py

fix sync_vector_env type-hint

---

gymnasium/envs/toy_text/frozen_lake.py
tests/envs/test_env_implementation.py

This PR adds a seed argument to the `generate_random_map()` function in FrozenLake.
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/127.

[FrozenLake] Add seed in random map generation

---

gymnasium/wrappers/monitoring/video_recorder.py

More context for this change here: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

Fix exception causes in video_recorder.py

---

gymnasium/envs/box2d/bipedal_walker.py
gymnasium/envs/box2d/car_dynamics.py
gymnasium/envs/box2d/car_racing.py
gymnasium/envs/box2d/lunar_lander.py
gymnasium/envs/classic_control/acrobot.py
gymnasium/envs/classic_control/cartpole.py
gymnasium/envs/classic_control/continuous_mountain_car.py
gymnasium/envs/classic_control/mountain_car.py
gymnasium/envs/classic_control/pendulum.py
gymnasium/envs/classic_control/utils.py
gymnasium/envs/mujoco/mujoco_rendering.py
gymnasium/envs/phys2d/cartpole.py
gymnasium/envs/phys2d/pendulum.py
gymnasium/envs/registration.py
gymnasium/envs/toy_text/blackjack.py
gymnasium/envs/toy_text/cliffwalking.py
gymnasium/envs/toy_text/frozen_lake.py
gymnasium/envs/toy_text/taxi.py
gymnasium/experimental/wrappers/lambda_observations.py
gymnasium/utils/env_checker.py
gymnasium/utils/play.py
gymnasium/utils/save_video.py
gymnasium/vector/async_vector_env.py
gymnasium/vector/utils/spaces.py
gymnasium/wrappers/frame_stack.py
gymnasium/wrappers/human_rendering.py
gymnasium/wrappers/resize_observation.py

@pseudo-rnd-thoughts  This is the continuation of #197 for the entire codebase.

Fix exception causes all over the codebase

---

gymnasium/envs/classic_control/utils.py
gymnasium/vector/utils/spaces.py

Fix formatting errors introduced in https://github.com/Farama-Foundation/Gymnasium/pull/205
@pseudo-rnd-thoughts

Fix formatting errors

---

gymnasium/envs/mujoco/ant_v4.py

`Ant` `use_contact_forces` obs and reward DOC

---

gymnasium/envs/mujoco/reacher_v4.py

Too lazy to write a description, just see the commits, it is 2 things

`MuJoCo.Reacher-v4` doc fixes

---

docs/api/experimental/functional.md
docs/content/release_notes.md
docs/index.md
docs/release_notes/gym_v0.19.0.md
docs/release_notes/gym_v0.20.0.md
docs/release_notes/gym_v0.21.0.md
docs/release_notes/gym_v0.22.0.md
docs/release_notes/gym_v0.23.0.md
docs/release_notes/gym_v0.23.1.md
docs/release_notes/gym_v0.24.0.md
docs/release_notes/gym_v0.24.1.md
docs/release_notes/gym_v0.25.0.md
docs/release_notes/gym_v0.25.1.md
docs/release_notes/gym_v0.25.2.md
docs/release_notes/gym_v0.26.0.md
docs/release_notes/gym_v0.26.1.md
docs/release_notes/gym_v0.26.2.md
docs/release_notes/gymnasium_v0.26.0.md
docs/release_notes/gymnasium_v0.26.1.md
docs/release_notes/gymnasium_v0.26.2.md
docs/release_notes/gymnasium_v0.26.3.md
docs/release_notes/gymnasium_v0.27.0.md

This PR adds release notes for Gym and Gymnasium

Add release notes page

---

gymnasium/envs/mujoco/hopper_v4.py

Just check the commit, it is a simple typo fix

`Mujoco/Hooper` doc minor typo fix

---

.pre-commit-config.yaml
docs/environments/classic_control.md
gymnasium/envs/box2d/bipedal_walker.py
gymnasium/envs/box2d/car_dynamics.py
gymnasium/envs/box2d/car_racing.py
gymnasium/envs/box2d/lunar_lander.py
gymnasium/envs/classic_control/acrobot.py
gymnasium/envs/classic_control/cartpole.py
gymnasium/envs/classic_control/continuous_mountain_car.py
gymnasium/envs/classic_control/mountain_car.py
gymnasium/envs/classic_control/pendulum.py
gymnasium/envs/mujoco/mujoco_env.py
gymnasium/envs/mujoco/mujoco_rendering.py
gymnasium/envs/phys2d/cartpole.py
gymnasium/envs/phys2d/pendulum.py
gymnasium/envs/toy_text/blackjack.py
gymnasium/envs/toy_text/cliffwalking.py
gymnasium/envs/toy_text/frozen_lake.py
gymnasium/envs/toy_text/taxi.py
gymnasium/experimental/wrappers/jax_to_numpy.py
gymnasium/experimental/wrappers/jax_to_torch.py
gymnasium/experimental/wrappers/lambda_observations.py
gymnasium/experimental/wrappers/numpy_to_torch.py
gymnasium/utils/play.py
gymnasium/utils/save_video.py
gymnasium/wrappers/monitoring/video_recorder.py
gymnasium/wrappers/resize_observation.py
pyproject.toml

- Replace `gymnasium[classic_control]` / `gymnasium[toy_text]` with `gymnasium[classic-control]` / `gymnasium[toy-text]`.
- Align letter cases in the error message with the `import` statement.
- Fix a typo: rgb_arrray -> rgb_array

Update prompt messages for extra dependencies

---

README.md

very minor fix for versioning in README

FIX: versioning in README.md

---

docs/index.md

Add a link to Comet's Gymnasium tutorial to the sidebar

Add Comet Tutorial

---

README.md

Add blurb about Comet's integration for Gymnasium.

Add Comet integration

---

gymnasium/envs/box2d/lunar_lander.py

1. Added more documentation to explain how the simulation works.
2. Clearly communicated the scaling factors that are applicable to the state vectors.
3. Added constants where applicable.
4. Disabled particle rendering, when the simulation is not run in human mode.

Lunar lander code clarity

---

gymnasium/envs/toy_text/blackjack.py

For consistency return type and as written at the documention, return type change Tuple(int, int, bool) to Tuple(int, int, int)
return type change Tuple(int, int, bool) to Tuple(int, int, int)
usable ace function at envs/toy_text/blackjack.py line: 28 return type to int

Fix Blackjack observation from boolean to int as expected 

---

gymnasium/envs/mujoco/ant_v4.py

Fixes/clarifies the description of the contact forces for Ant
it should the problem of https://github.com/Farama-Foundation/Gymnasium/issues/385 for example

`MuJoCo/Ant-v4` DOC fix contact_forces observation

---

docs/tutorials/training_agents/FrozenLake_tuto.py

This PR is a followup of https://github.com/Farama-Foundation/Gymnasium/pull/376. I noticed that the other tutorials in the [Training Agents](https://gymnasium.farama.org/tutorials/training_agents/) section had authorship + licensing information, so this PR does the same for the FrozenLake tutorial.

Update FrozenLake tutorial

---

gymnasium/envs/classic_control/pendulum.py

Removing extra $ signs for theta.

---

docs/conf.py

A merge to update Celshast with furo recent changes broke the edit button. This PR updates the `conf.py` to fix the problem.

Fix missing edit button

---

gymnasium/utils/passive_env_checker.py
tests/envs/test_envs.py
tests/utils/test_passive_env_checker.py

Finishes https://github.com/Farama-Foundation/Gymnasium/pull/401

Remove warnings

---

README.md

Fixing the Language of the Comet section of the readme

Update comet section readme

---

docs/content/basic_usage.md

Fix grammar/typos in intro to basic_usage

---

docs/environments/third_party_environments.md

Update third party envs versions.

Update third party envs: safety gymnasium

---

docs/environments/third_party_environments.md

Update third party environments documentation

Add DACBench third party environment

---

.github/workflows/build-docs.yml
.github/workflows/docs-manual-versioning.yml
.github/workflows/docs-versioning.yml

We pinned mujoco to 2.3.3 but I forgot to update the documentation then messed up fixing it two times, third time the charm

Fix build documentation 

---

.pre-commit-config.yaml
gymnasium/vector/utils/__init__.py

Pyright update caused the CI to start to fail, this fixes the issue

Fix pyright pre-commit

---

docs/environments/third_party_environments.md

mobile-env has already been listed as thrid-party environment in the Gymnasium docs.
Following the request by @elliottower in https://github.com/stefanbschneider/mobile-env/issues/26, I updated the `mobile-env` dependencies to support the latest version of gymnasium (part of mobile-env v2.0.0 release).
This PR updates the Gymnasium docs by moving mobile-env to the third-party environments with Gymnasium support.
Fixes https://github.com/stefanbschneider/mobile-env/issues/26

Add mobile-env as 3rd party env with gymnasium support

---

.gitignore
gymnasium/envs/toy_text/frozen_lake.py

forzen lake Truncation doc

---

docs/environments/mujoco.md

Changes this:
to be listed alphabetically.
It was bothering me.

[Documentation] Reorder `mujuco` env list to alphabetical

---

docs/environments/third_party_environments.md

This just adds pyflyt to the third party environments list.

Add pyflyt to third party

---

gymnasium/wrappers/monitoring/video_recorder.py

Remove env.close in VideoRecorder.close

---

docs/environments/third_party_environments.md

Updated stable-retro link in third_party_environments.md

---

bin/all-py.Dockerfile

For some reason, Box2d-py is now failing in CI

Install swig in docker

---

pyproject.toml

Remove the version restriction on pygame 
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/550

Remove the restrictions on pygame version

---

gymnasium/utils/performance.py

I just run `mypy` and found a couple of issues
this PR fixes them

type hint `utils/performance.py`

---

pyproject.toml

I missed it in https://github.com/Farama-Foundation/Gymnasium/pull/573

update `pyright` python version `3.7` -> `3.8`

---

tests/envs/mujoco/test_mujoco_custom_env.py

Fixes `pyright.TypeIssues`
Note: these issues are disabled in the CI by default

fix `pyright.TypeIssues` in  `test_mujoco_custom_env.py`

---

gymnasium/spaces/dict.py
tests/spaces/test_dict.py

Fixes https://github.com/Farama-Foundation/Gymnasium/issues/579

Fixed `key in Dict.keys()` always being false

---

gymnasium/envs/mujoco/mujoco_env.py
gymnasium/envs/mujoco/mujoco_rendering.py
gymnasium/envs/mujoco/reacher_v4.py

Fixes a few more `pyright.TypeIssues`

`MuJoCo` `Type Issues` fixes

---

gymnasium/core.py

There is a typo in that sentence, "reminding" should be "remaining."

Typo correction in core.py

---

docs/api/env.md
docs/api/registry.md
docs/api/spaces.md
docs/api/utils.md
docs/api/vector.md
docs/api/wrappers.md
gymnasium/functional.py
gymnasium/utils/env_checker.py
gymnasium/utils/play.py
gymnasium/utils/save_video.py
gymnasium/utils/seeding.py
gymnasium/utils/step_api_compatibility.py
gymnasium/wrappers/rendering.py
tests/wrappers/test_record_video.py

* Update ordering of `utils` functions in`utils.md` based on importance
* Add description to creating environments in `envs.md`
* Add descriptions to vector utility functions on `spaces.md`
* Fix maths in `capped_cubic_video_schedule`
* Improve documentation of functions in `utils.md`
* Improve docstrings of Functional environment API
* Fix example code in `utils/play`

Update docs 2

---

docs/tutorials/training_agents/blackjack_tutorial.py

The explanation mentions that the Q values are updated after every episode but the code updates the Q values after each step.
- [x ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)

Fix explanation of training agent

---

gymnasium/vector/vector_env.py
gymnasium/wrappers/lambda_observation.py
tests/envs/test_action_dim_check.py
tests/wrappers/test_jax_to_numpy.py
tests/wrappers/test_max_and_skip_observation.py
tests/wrappers/test_record_video.py

Attempts to reduce the number of CI warnings

Reduce the number of CI warnings 

---

tests/test_core.py

Old testing code for gym v0.21 that was never removed

Remove old testing code

---

docs/api/wrappers.md
gymnasium/core.py
gymnasium/vector/async_vector_env.py
gymnasium/vector/sync_vector_env.py
tests/test_core.py

Add `Wrapper.set_wrapper_attr` as a complementary function to `Wrapper.get_wrapper_attr` and helps solve https://github.com/Farama-Foundation/Gymnasium/issues/357 through changing the `SyncVectorEnv.set_attr` and `AsyncVectorEnv.set_attr` using `set_wrapper_attr` rather than `setattr`

Add `Wrapper.set_wrapper_attr` and fix issue 357

---

docs/environments/third_party_environments.md

I've added SimpleGrid, a simple and minimal grid environment for Gymnasium, to the list of third-party environments.
This change requires a documentation update
\-

Added SimpleGrid to the list of third-party environments

---

docs/api/wrappers.md
docs/api/wrappers/table.md
gymnasium/core.py
gymnasium/wrappers/__init__.py
gymnasium/wrappers/atari_preprocessing.py
gymnasium/wrappers/common.py
gymnasium/wrappers/numpy_to_torch.py
gymnasium/wrappers/stateful_action.py
gymnasium/wrappers/stateful_observation.py
gymnasium/wrappers/stateful_reward.py
gymnasium/wrappers/transform_observation.py

Tidy up the documentation in particular for wrappers

Improve the documentation

---

docs/api/wrappers.md
gymnasium/utils/passive_env_checker.py
gymnasium/wrappers/atari_preprocessing.py
gymnasium/wrappers/common.py
gymnasium/wrappers/jax_to_numpy.py
gymnasium/wrappers/jax_to_torch.py
gymnasium/wrappers/numpy_to_torch.py
gymnasium/wrappers/rendering.py
gymnasium/wrappers/stateful_action.py
gymnasium/wrappers/stateful_observation.py
gymnasium/wrappers/stateful_reward.py
gymnasium/wrappers/transform_action.py
gymnasium/wrappers/transform_observation.py
gymnasium/wrappers/transform_reward.py
gymnasium/wrappers/vector/dict_info_to_list.py
gymnasium/wrappers/vector/jax_to_numpy.py
gymnasium/wrappers/vector/vectorize_action.py
gymnasium/wrappers/vector/vectorize_reward.py

Add change logs to wrapper documentation along with linking to the vector version wrapper for those that exist

Add change logs to wrapper documentation

---

gymnasium/wrappers/rendering.py
pyproject.toml
tests/wrappers/test_record_video.py

Fixing CI issues of https://github.com/Farama-Foundation/Gymnasium/pull/715

Fix CI problems of #715

---

.github/workflows/build-docs.yml
.github/workflows/docs-manual-versioning.yml
.github/workflows/docs-versioning.yml
docs/api/experimental/functional.md
docs/requirements.txt

* Add missing dependencies (jax, torch)
* Update sphinx-gallery to version 0.14.0
* Fix `gymnasium.experimental.FuncEnv` doc

Small fixes to docs

---

docs/environments/third_party_environments.md

Environment: [qwop-gym](https://github.com/smanolloff/qwop-gym)

Add QWOP as a third-party environment

---

docs/environments/third_party_environments.md

Adds SuperTuxKart to the third-party environments

Update third_party_environments.md (SuperTuxKart)

---

gymnasium/wrappers/atari_preprocessing.py

In the updating of wrappers for v1.0.0, Atari preprocessing was generally ignored as it was a mess of code required a large amount of testing to ensure any changes worked. 
This PR just updates the type hinting and simplifies an if statement

Add type hinting to Atari Preprocessing

---

gymnasium/envs/mujoco/inverted_pendulum_v5.py

typo fix  inverted_pendulum xml_file argument

---

gymnasium/wrappers/rendering.py
tests/wrappers/test_record_video.py

For an unknown reason, the `RecordVideo` testing failed on another PR. 
I decided to investigate why and couldn't replicate the issue but found the testing for a key element of the project lacking in place. So I have procrastinated and added more testing

Improve `RecordVideo` wrapper testing

---

docs/environments/third_party_environments.md

The authors responded to a GitHub issue I created a while back and said it was complete, I checked and it indeed uses v28

Mark gym-pybullet-drones as using Gymnasium

---

gymnasium/envs/mujoco/inverted_double_pendulum_v5.py

typo fix inverted_double_pendulum_v5 rewards section

---

.pre-commit-config.yaml
gymnasium/envs/registration.py

introduces a couple of errors in `registration.py`

Remove `pyright` version limit for pre-commit

---

.pre-commit-config.yaml
gymnasium/envs/registration.py
gymnasium/utils/env_checker.py
tests/envs/mujoco/test_mujoco_v5.py
tests/envs/registration/test_make_vec.py
tests/envs/utils.py
tests/vector/utils/utils.py
tests/wrappers/test_jax_to_torch.py

Periodic update of the pre-commit configures using `pre-commit autoupdate` and `pre-commit run --all-files`

pre-commit autoupdate

---

gymnasium/envs/toy_text/blackjack.py

Fixes https://github.com/Farama-Foundation/Gymnasium/issues/772

Update the blackjack starting state in documentation

---

gymnasium/envs/mujoco/ant_v5.py

total mass was calculated with 
```py
import gymnasium
env = gymnasium.make("Ant-v5")
env.unwrapped.model.body_mass.sum()
```

[MuJoCo] [Documention] specify the size of the ant in it's description

---

pyproject.toml

I will work with the mujoco devs tomorrow to fix the bug, for now this should work

pin `mujoco <= 3.1.1`

---

pyproject.toml

pin `mujoco <= 3.1.1` (#913)

---

gymnasium/envs/mujoco/half_cheetah_v5.py

… consistent with the xml file.
Fixes #906
- [X ] Documentation only change (no code changed)

Fixed the description of Half Cheetah's observation space elements

---

gymnasium/envs/box2d/bipedal_walker.py

- refactor the heuristic used for the bipedal walker in a seperate class / function.
- this allows for greater re-usability if one wants to use this function elsewhere, e.g. to generate offline training data as it was the case for me.
- further, there is no explicit reason why the heuristics should be included in the training loop
**Please let me know about any changes you would like to see**

refactor BipedalWalker heuristics: extract heuristic in a separate function

---

pyproject.toml
tests/envs/mujoco/test_mujoco_v5.py

After a discussion with the `MuJoCo` devs (https://github.com/google-deepmind/mujoco/issues/1405#issuecomment-1946449031)

unpin `mujoco<=3.1.1`

---

gymnasium/envs/mujoco/humanoid_v5.py

the humanoid robot model was slightly changed in `gym==0.21.0`, this PR simply documents this the humanoid's version history

add disclaimer regarding `Humanoid-v2/-v3` reproducabiltiy

---

docs/environments/mujoco.md

Fixes https://github.com/Farama-Foundation/Gymnasium/issues/936

[Documentation] add mujoco version comparability section

---

gymnasium/envs/classic_control/cartpole.py
gymnasium/envs/phys2d/cartpole.py

[CartPole] add `sutton_barto_reward` to vector and jax

---

gymnasium/envs/mujoco/mujoco_env.py

refactor `set_state` into a single function, also update the docstring
note: `set_state` was not being tested, and this update does not change that

[MuJoCo] refactor `set_state` into a single function

---

gymnasium/envs/mujoco/humanoid_v5.py
gymnasium/envs/mujoco/humanoidstandup_v5.py

Fixes documentation of Humanoids action spaces
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/984

Fix documentation of `Humanoid`s action spaces

---

gymnasium/utils/env_checker.py

Fix `TorchToJax` to `TorchToNumpy` in `check_env`

Fix torch support in `check_env`

---

gymnasium/vector/async_vector_env.py

Since the `_raise_if_errors` function also returns a tuple, I included it in the return type hint.
Fixes #1015
| ![image](https://github.com/Farama-Foundation/Gymnasium/assets/54899900/69adb0a7-3709-4667-8955-01591d30a0d1) | ![image](https://github.com/Farama-Foundation/Gymnasium/assets/54899900/be8c3701-3c72-49c1-bab7-ad9e6ea42c35) |

Fix `_raise_if_errors` type hint

---

docs/api/vector/async_vector_env.md
docs/api/vector/sync_vector_env.md
docs/environments/third_party_environments.md
gymnasium/vector/async_vector_env.py
gymnasium/vector/sync_vector_env.py

The website external environment didn't include a top # so all the sub topics were all shown in the table of contents
At the same time, we fix `np_random` and `np_random_seed` issues

Update website external environments page

---

docs/environments/third_party_environments.md

Adding EV2Gym as a new third party environment in the documentation.

Update third_party_environments.md with EV2Gym

---

.github/dependabot.yml

Noticed a few actions used in the workflows here are outdated, proposing a Dependabot configuration to update - reference https://docs.github.com/en/actions/security-guides/using-githubs-security-features-to-secure-your-use-of-github-actions#keeping-the-actions-in-your-workflows-secure-and-up-to-date
Suggest enabling https://docs.github.com/en/code-security/dependabot/working-with-dependabot/about-dependabot-on-github-actions-runners#enabling-or-disabling-for-your-repository as well.

[Proposal] Dependabot configuration to update actions in workflows

---

.github/workflows/build-publish.yml
.github/workflows/build.yml
pyproject.toml
tests/vector/utils/test_shared_memory.py

With Tensorflow and PyTorch updated, we can add testing for Python 3.12 in CI

Add testing for Python 3.12

---

gymnasium/utils/play.py

Fixed documentation for play method in gymnasium.utils.play class for CarRacing-V2 example
#1096 

update utils.play docstring example

---

docs/environments/third_party_environments.md

Adds the [Craftium](https://github.com/mikelma/craftium/) project to the list of third-party environments.

Add Craftium to third-party environments

---

gymnasium/vector/async_vector_env.py
gymnasium/vector/sync_vector_env.py

- Avoid unnecessary reset in sync_vector_env.py
- Fix some typos and type hints in async_vector_env.py

Fix some small bugs in gymnasium.vector

---

tests/vector/utils/test_shared_memory.py

All test parameters will be skipped due to the wrong conditioning clause

Fixed bug in test_shared_memory.py

---

CITATION.cff
README.md
docs/index.md

With the Gymnasium Arxiv paper, this PR updates the readme, citation.cff and website with the paper details

Update citation to Gymnasium Arxiv paper

---

.github/workflows/build.yml
.pre-commit-config.yaml
gymnasium/spaces/dict.py
gymnasium/spaces/discrete.py
gymnasium/spaces/oneof.py
gymnasium/spaces/tuple.py
gymnasium/wrappers/stateful_observation.py
gymnasium/wrappers/stateful_reward.py
gymnasium/wrappers/transform_action.py
gymnasium/wrappers/transform_observation.py
gymnasium/wrappers/transform_reward.py
gymnasium/wrappers/vector/dict_info_to_list.py
gymnasium/wrappers/vector/stateful_observation.py
gymnasium/wrappers/vector/stateful_reward.py
gymnasium/wrappers/vector/vectorize_action.py
gymnasium/wrappers/vector/vectorize_observation.py

The doctest is failing for NumPy 2.0.1 as it appears that the `__str__` implementation changes were reverted back to the NumPy 1.x style

Update doctest for NumPy 2.0.1

---

docs/environments/third_party_environments.md

Add a fixed-wing UAV environment FlyCraft to the third party environments.

add FlyCraft to third party environments

---

docs/introduction/basic_usage.md

Minor Documentation fixes

---

docs/environments/third_party_environments.md

third_party_environments.md with permanemt discord link

---

docs/environments/third_party_environments.md

Update third_party_environments with Gym-Gridworld repo

---

pyproject.toml

change pyproject classifier dev status to `5 - Production/Stable`

---

README.md
docs/environments/third_party_environments.md

Hello,
We are happy to announce a new 3rd party environment, [generals-bots](https://github.com/strakam/generals-bots)!
The environment a fast-paced strategy environment where players compete to conquer their opponents' generals on a 2D grid.
Current [generals.io](https://generals.io) bot-development tools are either not maintained, undocumented or simply poorly written. There are many players in the community wondering whether there could be a ML/RL based agent, that would be stronger than `Human.exe` — a rule/heuristic based agent written in ~30k lines of code. This repository is an invitation for RL practitioners (and others) to develop their own agents and build new SotA!
There is also a small `README.md` modification that removes outdated roadmap reference.
I think it is also good to …

Add 3rd party environment

---

docs/introduction/train_agent.md

The first parameter of the BlackjackAgent example needs to be the environment.
This will save time for those copying this code as they learn while reading along.

Fix Train Agent doc, need env param

---

gymnasium/envs/box2d/car_racing.py

Typo in car_racing.py

---

docs/introduction/create_custom_env.md

Formatting error in create_custom_env.md

---

docs/introduction/record_agent.md

Just a typo fix with the word "periodclly" to "periodically"
- Documentation only change (no code changed)

Fix typo in record_agent.md

---

docs/tutorials/README.rst
docs/tutorials/gymnasium_basics/README.rst
docs/tutorials/training_agents/README.rst

Corresponding proposal number: #1256 
This pull request improved the documentation by including the links to the actual documentation.
Providing more clarity to the tutorials section.
Before:
After:
Before:
After:
Before:
After:

Adding links to the tutorials section #1256

---

docs/tutorials/third-party-tutorials.md

Added some third-party beginner tutorials that have received positive feedback from the community and are highly praised, primarily focusing on video content.
- [ ✔ ] Documentation only change (no code changed)

Added some popular third-party beginner tutorials。

---

docs/introduction/basic_usage.md

Fixes [#1357](https://github.com/Farama-Foundation/Gymnasium/issues/1357)

Update basic_usage.md to be more clear on installing swig for MacOS users

---

README.md

docs: added link and license badge

---

gymnasium/wrappers/rendering.py

When recording using the RecordVideo wrapper, numpy seems to have a memory leak. A parameter "gc_trigger" has been added, that allows running gc.collect() based on a user-defined condition, such as every 10 episodes.
I tested this feature with the following code. I'ts my first time doing a PR, so I'm not sure if this script should be added somewhere (especially regarding the Checklist, which specifically asks for tests) :
```
from gymnasium.wrappers import RecordEpisodeStatistics, RecordVideo
import psutil
import os
def get_memory_usage_mb():
process = psutil.Process(os.getpid())
return process.memory_info().rss / 1024 / 1024  # In MB
num_eval_episodes = 50
def run_eval(gc_trigger_flag):
env = gym.make("CartPole-v1", render_mode="rgb_array")
env = RecordVideo(
env, …
```

Added garbage collector on RecordVideo wrapper

---

docs/environments/third_party_environments.md

Add Minesweeper environment by markov-labs to the external environments list. This was inspired by the partially observable environmental nature of the game with some custom additions for optional added complexity. Discussed the addition with Mark (PseudoRnd) on the official Farama Foundation discord channel.
*The checklist doesn't apply for the change made only in the documentation.*

Add minesweeper gymnasium environment to third_party_environments.md

---

docs/introduction/basic_usage.md
docs/introduction/create_custom_env.md
docs/introduction/gym_compatibility.md
docs/introduction/migration_guide.md
docs/introduction/record_agent.md
docs/introduction/train_agent.md

Reviewing the introduction pages, they could use some improvements. 
This PR should make it easier for new RL students.

Improve the introduction page

---

.github/workflows/run-pre-commit.yml

Some future pyright checks that would pass locally could fail in the GitHub Actions workflow, since the runner environment currently doesn't have access to type information from dependencies. It also leads to weaker type checking overall, since type information from dependencies is silently converted to `Any` when they aren't available.
This PR adds a step to the pre-commit workflow to install all of Gymnasium's dependencies, which is a simpler solution than requiring workarounds in code to make checks pass.
Also fixes a typo with the `python-version` key.
This is a GitHub Actions workflow change, so local tests aren't applicable.
- ~[ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see …

Install numpy during pre-commit workflow.

---

docs/environments/third_party_environments.md

Hello,
This pull request adds the Gym4ReaL external environment to the website list.
Let me know if any changes are needed.

Add Gym4ReaL to Third-party Environments section of the Gymnasium website

---

gymnasium/wrappers/transform_observation.py
gymnasium/wrappers/vector/common.py
gymnasium/wrappers/vector/stateful_observation.py

Adds the missing warnings to vector wrappers

Fix the vector wrapper warnings

---

gymnasium/envs/toy_text/blackjack.py

⏱️ Runtime :   **`163 microseconds`**  **→** **`102 microseconds`** (best of `251` runs)
The optimization eliminates redundant `sum(hand)` calculations that were happening multiple times in the original code. 
**Key changes:**
- **Introduced `_hand_sum_and_usable_ace` helper function** that computes both the hand sum and usable ace status in a single pass, avoiding duplicate `sum(hand)` calls
- **Modified `_get_obs`** to call the helper once instead of separately calling `sum_hand()` and `usable_ace()`, which each performed their own sum calculations
- **Preserved original function signatures** for `usable_ace` and `sum_hand` while making them use the shared computation internally
**Why this is faster:**
In the original code, `_get_obs()` called both `sum_hand()` and `usable_ace()`. The …

Optimize `BlackjackEnv` `_get_obs`

---

docs/environments/mujoco.md

I have fixed a small spelling error.

Fixing minor spelling error

---

gymnasium/__init__.py
gymnasium/wrappers/vector/dict_info_to_list.py

Update to Gymnasium version to v1.2.1

Update to v1.2.1
