Farama-Foundation/Gymnasium

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/proposal.md
The templates still linked to openai/gym, now they link here.
There's an argument to revamp the templates as a whole since people seem to misunderstand them **a lot**, but that's not a high priority
=> Rename the repo link in the issue templates

docs/content/basic_usage.md, gymnasium/core.py
Fix the Basic Usage page docs, by updating the code, fixing it, and also fixing the grammar.
In the second commit I fixed also the API -> Core page, by removing deprecated docs, fixing grammar and inconsistencies 
=> Fix and Update Basic Usage's and Core page

gymnasium/envs/toy_text/cliffwalking.py, gymnasium/wrappers/record_episode_statistics.py, tests/wrappers/test_record_episode_statistics.py, tests/wrappers/test_vector_list_info.py
(Re-PR for gymnasium, this was reviewed and approved on the old gym repo [PR #3101](https://github.com/openai/gym/pull/3101)) 
This addresses two issues I've run into with RecordEpisodeStatistics
1) Silent list conversion in vectorized environments. Currently, RecordEpisodeStatistics converts terminated and truncated into lists, but obs and reward may still be arrays, and the new vectorized `info` interface uses arrays. I particularly run into this in my code if I do something like `dones.any()`. This PR leaves the underlying details of terminated/truncated alone by using NumPy array functionality.
2) Speed. Instead of looping through a potentially large batch of environments, this PR uses NumPy functions with their underlying vectorization to achieve the same task.
I considered building …
=> Faster EpisodeStatisticsRecorder, converted from gym PR

gymnasium/spaces/utils.py, tests/spaces/test_multidiscrete.py
Fixes integer overflow in the flatten function when dtype is small. 
The current code will calculate the offsets as is, overflowing the max integer value and going to negatives. Once this is passed to `one_hot` we get an error as per the linked issue.
```
File "C:\Users\user\Anaconda3\envs\TRG\lib\site-packages\gym\spaces\utils.py", line 90, in _flatten_multidiscrete
onehot = np.zeros((offsets[-1],), dtype=space.dtype)
ValueError: negative dimensions are not allowed
```
#53 
```
import gym
space = gym.spaces.MultiDiscrete([101, 101, 101, 101], dtype=np.int8)
x = space.sample()
y = gym.spaces.flatten(space, x)
x = gym.spaces.unflatten(space, y)
print(x)
```
```
[82 52 50 66]
```
=> Fix integer overflow in MultiDiscrete.flatten()

docs/content/environment_creation.md
0.26.0 not on pypi
(these tutorials should really link to code rather than be written into the md files)
=> Update gymnasium version in environment creation tutorial

docs/environments/mujoco.md
added instructions for MuJoCo v3 and older
source:
https://discord.com/channels/961771112864313344/961772009770074142/1032587824626675722
did not provide instructions for MuJoCo v3 and older
`pip install gymnasium[mujoco]` does not work for mujoco-v3
note: it might be a good idea to add something like `pip install gymnasium[mujoco-old]` that would install `mujoco-py` instead of `mujoco`
Doc Change
=> added instructions for mujoco v3 and older

tests/envs/test_envs.py, tests/envs/utils.py
- Adds some atari environments to tested environments (if gym and ale are available)
- Removed definition of `minimum_testing_env_specs`, which was dead code, also didn't make sense (compared specs to strings, I think)
- Atari environments are currently not being tested for `render_mode` because `GymEnvironment` doesn't support that kwarg
Tests are currently not passing locally, which seems to be due to an unrelated problem
=> Added Atari environments to tests, removed dead code

gymnasium/envs/mujoco/mujoco_env.py
Current error message forces user to add extra debugging code for info that's already available
=> MujocoEnv: Include shape in error message

pyproject.toml, setup.py, tests/envs/test_envs.py, tests/envs/test_gym_conversion.py, tests/envs/utils.py
We add `gym[testing, atari, accept-rom-license]` to the testing requirements to make `test_gym_conversion` and Atari tests run in CI.
=> Added atari tests to CI, fixed test_gym_conversion that was failing due to missing ROMs

gymnasium/wrappers/monitoring/video_recorder.py, gymnasium/wrappers/record_video.py, tests/wrappers/test_video_recorder.py
If user forgets to call `close`, and the VideoRecorder is deleted by the garbage collector, the class tries to save the video, but it raises an error (and it is not easy to understand the reason). With this PR, RecordVideo just warns the user that the last video is not saved and to call close. 
It also adds a parameter `disable_logger` to disable MoviePy messages.
=> fix: remove auto close feature in VideoRecorder

gymnasium/envs/mujoco/__init__.py
Fixes #103 
The module import `__init__.py` for the mujoco environments imported the `mujoco_rendering.py` classes, which depend on the `mujoco` package. If only installing the `mujoco_py`environment dependencies  with `pip install gymnasium[mujoco_py]` , thie rendering module shouldn't be imported because ModuleNotFoundError for "mujoco" will be raised.
=> Remove Mujoco rendering import

gymnasium/envs/box2d/car_racing.py, gymnasium/utils/env_checker.py, gymnasium/utils/passive_env_checker.py, tests/envs/test_gym_conversion.py, tests/testing_env.py
Implements #79 
Some tests are still failing due to incomplete testing environments.
The `_check_render_return` function is very ugly but I don't think there is a much better way. Typically, we would use dicts for something like this, but for rgb_array we need short-circuiting to check the structure of the returned array without raising exceptions if it is unexpected.
=> Added testing for render return

gymnasium/utils/seeding.py
Identical changes to [pull request 3128 on OpenAI Gym repository](https://github.com/openai/gym/pull/3128).
Pull requested repeated here:
Changed error message produced when `seed` argument of `env.reset(seed=seed)` is the incorrect type to include the *type* of the incorrect seed rather than the *value*. This is in line with most other Python error messages.
Fixes #3127
Bug fix (non-breaking change which fixes an issue)
```
import gym
rng = np.random.default_rng()
seed = rng.integers(2**32)
env = gym.make("MountainCarContinuous-v0")
env.reset(seed=seed)
```
|----------|--------|
| `gym.error.Error: Seed must be a non-negative integer or omitted, not 1407292551` | `gym.error.Error: Seed must be a non-negative integer or omitted, not <class …
=> Change seeding error message to report seed type

gymnasium/__init__.py, gymnasium/spaces/__init__.py
Pyright complains that `gym.wrappers` is a private import, the reason for this is that `wrappers` is not included in the root `__init__.py`'s `__all__`.
In this PR, I have updated the `__all__` to include all of the imported items in the `__init__.py`
In addition, this PR adds the registry to the `__all__` like `make`, `register` and `spec`. We might want to think about making it a property to avoid users writing over environment specs
=> Fix `__all__` in root `__init__.py`

gymnasium/utils/play.py, tests/utils/test_play.py
This PR addresses https://github.com/Farama-Foundation/Gymnasium/issues/126
I just replaced the error message with an actual exception.
I guess `logger.error` can be a somewhat confusing name for a function that only does logging. Searching through the repo, https://github.com/Farama-Foundation/Gymnasium/blob/5674a52d4c4d7cca9f169db561622b8d3e49bd65/gymnasium/utils/save_video.py#L86 seems to have the same problem.
=> Fix `play` assertion error

gymnasium/wrappers/monitoring/video_recorder.py, gymnasium/wrappers/record_video.py
Fixed a bug where the `RecordVideo` wrapper was trying to retrieve the non-existing attribute `last_frame` from `VideoRecorder` causing recordings to fail. This pull request reintroduces the `last_frame` attribute resolving the issue.
=> Fixed render bug in RecordVideo wrapper

gymnasium/__init__.py, gymnasium/envs/__init__.py, gymnasium/envs/registration.py, tests/envs/test_pprint_registry.py
Added a function that lists all the current environments supported/present, neatly.
Resolves #75 
| ![Screenshot 2022-11-12 at 11 28 30 AM](https://user-images.githubusercontent.com/43489154/201471864-12b239b2-cb49-4d53-85b7-fef259863ae3.png) | ![Screenshot 2022-11-12 at 11 29 25 AM](https://user-images.githubusercontent.com/43489154/201471892-10b49749-8a19-4257-97f9-d8a78650703d.png) |
=> Added list envs function (pretty print envs)

gymnasium/envs/toy_text/frozen_lake.py
Precise that is_slippery is true by default.
Fixes # (135)
=> Documentation Frozen Lake : precise is_slippery true by default

docs/environments/third_party_environments.md
I was looking for a gym environment to create an env from the matrices of a discrete MDP (P_0(s), P(s'|s, a), R(s'|s, a)). 
After looking around, I didn't find any, so I created it!
My third-party env is available [on github](https://github.com/Paul-543NA/matrix-mdp-gym) and [Pipy](https://pypi.org/project/matrix-mdp-gym/).
It is pretty common for people to describe discrete MDPs with these matrices and have them available, this environment provides an easy way to turn those into a gym env and get all the benefits of a standard API.
This PR adds the [matrix-mdp](https://github.com/Paul-543NA/matrix-mdp-gym) environment to the `docs/environments/third_party_environments.md` file.
=> Matrix mdp third party

gymnasium/envs/registration.py, gymnasium/error.py
Addressing https://github.com/Farama-Foundation/Gymnasium/issues/92
This also introduces a change: now `UnsupportedMode` is raised if 'render_mode` is invalid (previously we showed only a warning). 
Side question: are the make `overloading` useful? It seems they introduce a bit of noise in the file just for having a more specific typing; a general return type `Env` works fine too
=> ENH: clean make function

gymnasium/spaces/utils.py
Just added a note about unflattening a sample from a flattened space.
Fixes #102
=> Flatten space docstring note about unflattening samples

gymnasium/spaces/discrete.py, gymnasium/spaces/utils.py
The `Discrete` class definition return type is `int` while the space `dtype` is `np.int64`. 
This PR makes the `Discrete` type consistent with `np.int64`.
=> Change discrete dtype to np.int64

docs/environments/toy_text.md, gymnasium/envs/toy_text/blackjack.py, gymnasium/envs/toy_text/cliffwalking.py, gymnasium/envs/toy_text/frozen_lake.py, gymnasium/envs/toy_text/taxi.py
Updates the toy_text docstrings to have better consitency and more information. As discussed on Discord. No dependcies required.
No related issue.
n/a
=> Update docstrings for improved documentation

docs/api/spaces/utils.md, gymnasium/spaces/dict.py, gymnasium/spaces/sequence.py, gymnasium/spaces/tuple.py, gymnasium/spaces/utils.py
- Some bullet point lists weren't rendered correctly because an empty line was missing
- Some places used single backticks instead of double
- Added some links to other parts of the docs via :class: :mod: etc...
- We should put documentation of flattening functions first before talking about flatdim
=> Fixed formatting of spaces docs

docs/api/wrappers.md, docs/api/wrappers/action_wrappers.md, docs/api/wrappers/misc_wrappers.md, docs/api/wrappers/observation_wrappers.md, docs/api/wrappers/reward_wrappers.md, docs/tutorials/implementing_custom_wrappers.py, gymnasium/core.py, gymnasium/wrappers/__init__.py
- Some descriptions of what wrappers do was moved from doctoring of superclass to module docstring
- Examples of wrapper implementations were moved from docstrings to a tutorial
- Removed the titles for each individual wrapper in the docs
=> Updated Wrapper docs

gymnasium/vector/async_vector_env.py
There is a minor bug in `AsyncVectorEnv.step_wait`.  Here's what happens:
1. If an exception is thrown by the step function of an env inside the worker...
2. ...the worker catches the exception and sends `(None, False)` back through the pipe to the `AsyncVectorEnv`.
3. `AsyncVectorEnv.step_wait` receives the message from the pipe and unpacks it as `result, success = pipe.recv()`.  At this point `result = None` and `success = False`.
4. AsyncVectorEnv.step_wait attempts to unpack `result` further using `obs, rew, terminated, truncated, info = result`
5. But, because `result` is `None`, this immediately throws a `TypeError` and bypasses the normal error handling using `_raise_if_errors`.
6. This means exceptions thrown inside the step method of vectorized envs do not get caught correctly, …
=> checking success before splitting result in step_wait

gymnasium/envs/mujoco/ant_v4.py
source: https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/ant.xml#L71
=> Fix `MuJoCo.Ant` action order in DOC

gymnasium/utils/env_checker.py
This allows checking for environments that are not built through `make` to pass.
=> Change env checker assertation to warning

gymnasium/envs/registration.py, tests/envs/test_make.py, tests/envs/utils_envs.py
If an environment doesn't have static metadata containing the render modes but a user tries to create an environment then an error will be raised. This error is replaced by a warning.
A test has been added to check this
=> Revert `make` error when render mode is used without metadata render modes

gymnasium/envs/box2d/lunar_lander.py
Improve model training performance by only calculating particles when in a render mode. Initial results vary between 1.5x - 1.75x speed improvement.
Fixes #170
- Bug fix (non-breaking change which fixes an issue)
```shell
$ python -m ml-stuff.lunar_lander_turbo --seed 44
Training took 67.50 seconds (baseline)
Training took 44.39 seconds (with_change)
1.52x faster
$ python -m ml-stuff.lunar_lander_turbo --seed 88
Training took 73.72 seconds (baseline)
Training took 42.09 seconds (with_change)
1.75x faster
$ md5 ppo_lunar_lander_with_change-44/policy.pth ppo_lunar_lander_baseline-44/policy.pth
MD5 (ppo_lunar_lander_with_change-44/policy.pth) = 46266d319de7912428268cccff20d966
MD5 (ppo_lunar_lander_baseline-44/policy.pth) = 46266d319de7912428268cccff20d966
$ md5 …
```
=> fix: Improve LunarLander-v2 `step` performance by >1.5x (#170)

gymnasium/wrappers/step_api_compatibility.py, tests/wrappers/test_step_compatibility.py
This PR adds support for vector environments in StepAPICompatibility wrapper. Previously, the wrapper was incompatible due to not passing proper flag to the underlying `step_api_compatibility` utility function.
Fixes #237 
=> Added vector env support to StepAPICompatibility wrapper.

gymnasium/spaces/sequence.py, tests/spaces/test_sequence.py
This allows the Sequence space to accept numpy arrays of size `[n, *base_size]` if the feature space of the Sequence is `Box(shape=base_size)`.
=> Allow sequence to accept stacked np arrays if the feature space is Box

setup.py
Long description was removed from the setup.py to toml change earlier, this PR adds it back.
=> Add back long description to setup

docs/tutorials/environment_creation.py
The link at https://github.com/Farama-Foundation/Gymnasium/blob/8f0baf62aa13c69c77dc00bed0060e09d700890a/docs/tutorials/environment_creation.py#L23 was redirecting to 404.
I changed it to redirect to https://gymnasium.farama.org/api/env/
Fixes #231 
=> docs(tutorials): fixed environment creation link

gymnasium/vector/async_vector_env.py
The type of info returned by `AsyncVectorEnv.reset` should be `dict` and not `List[dict]`
=> FIX: return type of AsyncVectorEnv.reset

gymnasium/wrappers/resize_observation.py, tests/wrappers/test_resize_observation.py
The `ResizeObservation` wrapper silently becomes buggy when passed an environment that produces two-dimensional observations, such as the output of `GrayscaleObservation` with `keep_dim=False` (the default), since it sets the `observation_space` to be two-dimensional (WxH), but actually produces three-dimensional output (WxHx1).
I changed the `observation` method to keep the shape, whether it be two- or three-dimensional. I also added extra checks in the constructor to make sure that the input is either two- or three-dimensional, since `cv2.resize` does not work otherwise.
Here is some code that demonstrates the bug:
```python
from gymnasium.wrappers import GrayScaleObservation, ResizeObservation
def assert_space_is_consistent(env):
obs_shape = env.reset()[0].shape …
```
=> ResizeObservation: fix silent bug on 2-dimensional observations.

gymnasium/wrappers/resize_observation.py
See #230
It got merged before I could look at it again, so just fixing two small annoyances:
1. `self.shape` was assigned twice
2. `2 <= dims <= 3` was replaced with `dims == 2 or dims == 3` to make it a bit obvious what the intention is
=> Minor fixes for the resize observation wrapper

gymnasium/envs/registration.py, gymnasium/utils/play.py, gymnasium/vector/__init__.py, gymnasium/vector/async_vector_env.py, gymnasium/vector/utils/misc.py, gymnasium/vector/utils/numpy_utils.py, tests/spaces/test_spaces.py, tests/testing_env.py, tests/utils/test_env_checker.py, tests/utils/test_passive_env_checker.py
This fixes all instances of annotations of `var: callable` to `var: Callable`. It also adds the relevant import from `collections.abc` or `typing` depending on the presence of the `__future__` import. I've also tried adding the parameters/return types, but they are fairly complex so I didn't manage for some of them.
Type annotations
=> Fix type annotations of `callable` to `Callable`

docs/tutorials/training_agents/blackjack_tutorial.py
This is a suggestion for doc improvement.
The use of convolution in average calculation (in the blackjack tutorial) doesn't jump out unless you've used the operation in the past. Felt a comment might aid someone else a bit lost as to why  `np.convolve` is used
=> Doc improvement: add comment describing what convolve does

gymnasium/spaces/utils.py, tests/spaces/test_utils.py
Provide more explicit error messages for failing unflattening of Discrete and Multidescrete values.
- An error would be raised anyway for the cases that are catch.
- Values mapping itself is not checked, see #102 for the full discussion.
- Error messages try also to contextualize and remind that not all samples from a flattened space can be unflattened (enforcing the state of the flattening feature) in order to help users that may think they are (I did even having quickly walked among doc).
Related to #102 
=> Add explicit error messages when unflatten discrete and multidiscrete fail

gymnasium/experimental/wrappers/lambda_reward.py, tests/experimental/wrappers/test_normalize_reward.py
Should resolve #271 in a minimal way with simple tests.
=> Fix experimental normalize reward wrapper

docs/api/spaces.md
Switch references of the `MultiBinary` and `MultiDiscrete` classes in list of fundamental spaces to match their corresponding description.
Fixes #275 
=> Switch references of the MultiBinary and MultiDiscrete classes in documentation

gymnasium/envs/box2d/lunar_lander.py
fix AttributeError of  `lunar_lander.py`
when I run `python gymnasium/envs/box2d/lunar_lander.py`, it raise,
```shell
AttributeError: 'NoneType' object has no attribute 'id'
```
`self.spec` is `None`, so it has no attribute 'id'.
| ![image](https://user-images.githubusercontent.com/44900829/213724047-436d183a-f415-4084-816f-5d35a766f828.png)| ![image](https://user-images.githubusercontent.com/44900829/213724258-1966a2e1-470a-4c77-89a1-923178d7dc8f.png)|
=> Fix AttributeError in lunar_lander.py

docs/content/gym_compatibility.md, gymnasium/envs/__init__.py, gymnasium/envs/registration.py, gymnasium/wrappers/compatibility.py, tests/envs/test_compatibility.py
In order to de-couple shimmy and gymnasium, such that they are not core dependencies of both.
For backward compatibility, we register dummy / fake gym compatibility environments.
However, it was founded in shimmy that the v22 compatibility is actually for v21. 
Therefore, shimmy is updating to use `GymV21Compatibility` rather than `GymV22Compatibility`.
As the shimmy is not updated yet, we need to keep use the shimmy V0.22 environments but as soon as this is released then we can update shimmy and then need to fix this issue
=> Change `GymV22Compatibility` to `GymV21Compatibility` 

docs/index.md, docs/scripts/utils.py
Ignore `GymV21Environment` when building environments docs. Fixes failing workflow
=> Ignore GymV21Environment when building environments docs

tests/vector/test_async_vector_env.py, tests/vector/test_sync_vector_env.py, tests/vector/test_vector_env.py, tests/vector/test_vector_env_info.py, tests/vector/test_vector_env_wrapper.py, tests/vector/test_vector_make.py
This should remove all changes to the old vector API tests
=> New vector API - revert old tests

gymnasium/utils/__init__.py, gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, gymnasium/vector/vector_env.py, tests/vector/test_async_vector_env.py, tests/vector/test_sync_vector_env.py
- Made some changes so that pyright doesn't think `Env.step()` is supposed to return `None`.
- `infos` was mistyped as a `list[dist]` when it should be `dict`. Fixed the type hint and verified that the types are correct in the unit tests.
- Exposed the `colorize` and `EzPickle` utils
=> Type hint fixes and added __all__ dunder

gymnasium/envs/registration.py
`**kwargs` and `vector_kwargs` were mixed up between the different vectorization modes, now they are not.
=> Properly handle different kwargs in the new vector API

gymnasium/spaces/box.py, gymnasium/spaces/dict.py, gymnasium/spaces/discrete.py, gymnasium/spaces/graph.py, gymnasium/spaces/multi_binary.py, gymnasium/spaces/multi_discrete.py, gymnasium/spaces/sequence.py, gymnasium/spaces/space.py, gymnasium/spaces/text.py, gymnasium/spaces/tuple.py, gymnasium/spaces/utils.py
Removed `reportInvalidTypeVarUse` and `reportGeneralTypeIssues` with pyright and fixed the new raised issues.
Files that are covered without errors: 
=> Fix type hints errors in gymnasium/spaces

docs/conf.py, gymnasium/spaces/dict.py, gymnasium/wrappers/step_api_compatibility.py
As stated in #320, the documentation Gymnasium website contains duplicated content that can be confusing. Both the docstring from the `Class` and the `__init__` are displayed, meaning there is often a sentence repeated twice.
To keep the documentation the same, I just added a parser to the Sphinx `conf.py` to remove any lines that are written before a `Args` in the docstring. 
```
class TransformReward(RewardWrapper):
"""Transform the reward via an arbitrary function.
Warning:
If the base environment specifies a reward range which is not invariant under :attr:`f`, the :attr:`reward_range` of the wrapped environment will be incorrect.
Example:
>>> import gymnasium as gym
>>> from gymnasium.wrappers import TransformReward
>>> env = gym.make("CartPole-v1")
>>> env = TransformReward(env, …
```
=> Add docstring parser to remove duplicate in Gymnasium website

docs/content/basic_usage.md
Changed
> Gymnasium has support for a major of possible spaces are users need
to
> Gymnasium has support for a majority of possible spaces users might need
=> Fix grammatical mistake in the documentation

tests/envs/test_compatibility.py
Shimmy released v0.2.1, which caused the CI to break for the compatibility test. This fixes it
=> Fix CI due to shimmy bump

gymnasium/envs/mujoco/ant_v4.py
clarifies the fact that `use_contact_forces` does not exist on previous versions
Downside: it increases the complexity of the DOC for people not interested in v3 or older
- [DOES NOT APPLY] I have commented my code, particularly in hard-to-understand areas
- [DOES NOT APPLY] I have made corresponding changes to the documentation
- [[DOES NOT APPLY] My changes generate no new warnings
- [[DOES NOT APPLY] I have added tests that prove my fix is effective or that my feature works
- [DOES NOT APPLY] New and existing unit tests pass locally with my changes
=> `MuJoCo/Ant` clarify the lack of `use_contact_forces` on  v3 (and older)

gymnasium/core.py, gymnasium/experimental/wrappers/common.py, gymnasium/experimental/wrappers/conversion/jax_to_numpy.py, gymnasium/experimental/wrappers/lambda_action.py, gymnasium/experimental/wrappers/lambda_observations.py, gymnasium/experimental/wrappers/lambda_reward.py, gymnasium/experimental/wrappers/rendering.py, gymnasium/experimental/wrappers/stateful_action.py, gymnasium/experimental/wrappers/stateful_observation.py, gymnasium/utils/passive_env_checker.py, tests/experimental/wrappers/test_record_video.py
As noted in https://github.com/DLR-RM/stable-baselines3/pull/1327 and tianshou, the wrapper type hints were raising type checker issues.
This PR solves those issues by changing the wrapper type hints to 
`class Wrapper(Env[WrapperObsType, WrapperActType], Generic[WrapperObsType, WrapperActType, ObsType, ActType]):`
For example type hinting that passes mypy and pyright type checkers
```python
from typing import TypeVar, Generic
from abc import abstractmethod
ObsType = TypeVar("ObsType")
ActType = TypeVar("ActType")
class Env(Generic[ObsType, ActType]):
@abstractmethod
def step(self, action: ActType) -> ObsType:
pass
@abstractmethod
def reset(self) -> ObsType:
pass
WrapperObsType = TypeVar("WrapperObsType")
WrapperActType = TypeVar("WrapperActType")
WrappedEnvObsType = …
```
=> Fix the wrapper type hints

gymnasium/core.py, gymnasium/envs/registration.py, gymnasium/wrappers/autoreset.py, gymnasium/wrappers/env_checker.py, gymnasium/wrappers/order_enforcing.py, gymnasium/wrappers/time_limit.py, tests/envs/registration/test_env_spec.py, tests/envs/registration/test_make.py, tests/test_core.py, tests/wrappers/test_time_limit.py
As noted by https://github.com/DLR-RM/stable-baselines3/pull/1327#issuecomment-1445219678, there are significant backward compatibility issues with https://github.com/Farama-Foundation/Gymnasium/pull/292
This PR updates `EnvSpec` such that it is a "full description of the whole env". Using the `EnvSpec` in `make` is now identical to `make(str)` as before. Critically, the difference with `make` in v0.27 is that the `EnvSpec` changes with each wrapper applied, including the default wrappers. As a result, `env.unwrapped.spec`'s `EnvSpec` has all parameters disabled such that `gym.make(env.unwrapped.spec)` is equivalent to just the base environment. 
The advantage of this implementation is that users can define an environment, `env` and perfectly replicate each stage
```python
while env is …
```
=> Update `EnvSpec` to improve backward compatibility

gymnasium/envs/mujoco/mujoco_env.py, gymnasium/envs/registration.py, gymnasium/experimental/vector/utils/space_utils.py, gymnasium/utils/passive_env_checker.py, gymnasium/wrappers/compatibility.py, pyproject.toml, tests/envs/functional/test_core.py, tests/envs/registration/test_make.py, tests/envs/test_compatibility.py, tests/envs/test_envs.py, tests/testing_env.py, tests/utils/test_passive_env_checker.py
This PR adds changes in the tests to remove warnings (256 warnings -> 55 warnings): 
- Some warnings are changed from `UserWarning` to `DeprecationWarning`
- Typo fixes
- `env.reset` from old api is added to be rightly tested
- Move "The environment is out of date" warning to `DeprecationWarning` with regex
- Mask `DeprecationWarning` in `pytest`
=> Reduce numbers of warnings in CI 

pyproject.toml
Correct the filterwarnings in the pytest configuration to only filter internal `DeprecationWarning`
=> Modify filterwarnings in Pytest configuration

gymnasium/core.py
This PR adds a note to the docs to explicitely say how to seed the action space.
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/185.
=> Add a note on how to seed the action space

gymnasium/envs/box2d/lunar_lander.py
Revert changes in Lunar Lander environment's observation space changes. Now the observation space is same as that of `gym` version `0.23`
Fixes #377 
=> Update observation space bounds of LunarLander environment. 

docs/tutorials/gymnasium_basics/vector_envs_tutorial.py
Running vector_env_tutorial.py on jupyter notebook doesn't trigger the following error. 
But on the .py file, it caused. I confused jupyter and interactive mode on vscode. At first, I thought they are identical.
But maybe it isn't. 
.ipynb  file ran succesfully but .py file on interactive 
Therefore I add the notice on the head of the vector_env_tutorial.py.
The content is that adding `if name == "main"` from gym.vector to the end to avoid error on multiprocessing
(Fixes https://github.com/Farama-Foundation/Gymnasium/issues/309)
The issue was triggered at gym.vector.make and gym.vector.AsyncVectorEnv
I ran on Python 3.10 and my computer is 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
Case 1: Just running .py file
Case 2: …
=> Update vector_envs_tutorial.py 

gymnasium/utils/step_api_compatibility.py
The problem is that gym.Env defines step return as Tuple[..., SupportsFloat, ...], and this then can't be passed into functions of `step_api_compatibility`. Alternative to my fix would be to define centrally what is a step return, and reuse the type alias in both places.
=> Use SupportsFloat in step_api_compatibility

gymnasium/__init__.py
For some reason, `import gymnasium` followed by `gymnasium.vector` fails as the module is not imported in `gymnasium/__init__.py`. More alarming this is not picked up by the CI
=> Import `vector` in `gymnasium.__init__`

docs/environments/third_party_environments.md
Minor bugfix: remove the second entry on the documentation website sidebar "Third Party Environments using Gym".
Sorry about this, I thought I committed this as well last night but I forgot to. Had kept the H1 tag originally because otherwise the subcategories (robotics, racing, etc) would be the same size, but didn't realize it would make a separate entry in the sidebar for that H1 tag. The subcategories being the same size doesn't look too bad either, it's probably better to keep the top of the page as the only H1 anyways.
=> Remove second sidebar entry "Third Party Environments using Gym"

docs/conf.py
The documentation filter I added before is too large, and removes too much content like : 
- https://gymnasium.farama.org/api/experimental/wrappers/#gymnasium.experimental.wrappers.TimeAwareObservationV0
- https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.RecordEpisodeStatistics
I fixed it to be stricter and it should working as expected
=> Fix the doc filter to check only args values

docs/scripts/gen_mds.py, gymnasium/envs/__init__.py, gymnasium/experimental/wrappers/rendering.py, gymnasium/wrappers/human_rendering.py
Currently the jax environment have no consistent environment names for registration.
This PR updates the environments to use a phys2d and tabular as the namespace
=> Update jax environment names

gymnasium/envs/mujoco/mujoco_env.py
This fixes the incorrect value passed to the argument `nstep` in `_step_mujoco_simulation` function of class `MujocoEnv`, according to the discussion of issue https://github.com/Farama-Foundation/Gymnasium/issues/420:
Fixes # (420)
=> Fix the wrong nstep in _step_mujoco_simulation function of class MujocoEnv

docs/index.md
- adds a video to showcase 6 different environments: BipedalWalkerHardcore, Breakout, CarRacing, CartPole, LunarLander and Humanoid
- the video acts as a GIF (it is played in a loop and saved as mp4 because this is smaller compared to saving a GIF)
- edited the text
=> Update the frontpage (new video with different envs)

gymnasium/envs/classic_control/cartpole.py
The maximum reward is equal to the maximum episode length.
=> Update CartPole reward documentation

docs/content/gym_compatibility.md
The previous code throws an error:
```
env = gymnasium.make("GymV21Environment-v0", env_id="CartPole-v1", make_kwargs={"length": 1}, render_mode="human")
/Users/elliottower/anaconda3/envs/shimmy/lib/python3.9/site-packages/gymnasium/envs/registration.py:787: UserWarning: WARN: The environment is being initialised with render_mode='human' that is not in the possible render_modes ([]).
logger.warn(
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/elliottower/anaconda3/envs/shimmy/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 813, in make
raise e
File "/Users/elliottower/anaconda3/envs/shimmy/lib/python3.9/site-packages/gymnasium/envs/registration.py", line 801, in make
env = env_creator(**env_spec_kwargs)
File …
```
=> Update gym_compatibility.md to fix broken example

gymnasium/envs/mujoco/mujoco_rendering.py
Fixes #438
Fixes `TypeError` exception that can appear when finishing with an environment that was rendered.
Fixes #438 
=> Fix TypeError when closing rendering

pyproject.toml
In the installed package the `assets/` directory is missing in `envs/phys2d/`, because it is not listed at `tool.setuptools.package-data` in `pyproject.toml`. This leads for `tests/envs/test_rendering.py::test_render_modes[PendulumJax-v0]` to an error: "FileNotFoundError: No such file or directory: `'/path/to/my/env/lib/python3.9/site-packages/gymnasium/envs/phys2d/assets/clockwise.png'`." caused from `envs/phys2d/pendulum.py:136`. This commit should fix the test.
=> Add missing phys2d asset in setup

tests/envs/functional/test_jax.py, tests/experimental/functional/test_func_jax_env.py, tests/experimental/functional/test_jax_blackjack.py, tests/experimental/functional/test_jax_cliffwalking.py, tests/experimental/wrappers/test_init_shorten_import.py, tests/experimental/wrappers/test_jax_to_numpy.py, tests/experimental/wrappers/test_jax_to_torch.py
Jax and PyTorch are optional dependencies. As such, tests importing them, should also be optional. This PR skips these tests, if the module is missing. This is an issue, because Jax is not available for Windows from conda-forge or PyPI and PyTorch is not available for Windows from conda-forge. A similar patch has been applied in https://github.com/conda-forge/gymnasium-feedstock/pull/28.
The same actually holds for OpenCV, which is required in [this test](https://github.com/Farama-Foundation/Gymnasium/blob/main/tests/wrappers/test_atari_preprocessing.py#L51). However, OpenCV is well available and skipping the test is not so easy, because it throws in the pytest parametrization.
→ Enhances windows compatibility of test suite.
→ Not required.
→ …
=> Skip Jax and PyTorch tests if module is missing

docs/index.md
Effectively reverts the iffy part of #426 and replaces #471.
We decided not to use a video that requires attribution to a specific training library. For the moment we can stick with the old gif, maybe we will replace it with a different video in the future.
=> Revert the front page to the old gif

gymnasium/envs/mujoco/walker2d_v4.py
1) #Description
1.1) no longer cites "Infinite Horizon Model Predictive Control for Nonlinear Periodic Tasks" since this only includes hopper, and not walker
1.2) fix counting
1.3) fix incoherent sentence
2) #Observation space
2.1) renamed `top` → `torso`, since `top` was never defined and was confusing
3) #Reward
3.1) fix sentence
=> Fix `walker2d` Description and typos

docs/index.md
Minor CSS changes to make header text aligned to the left on mobile.
Also added 10px padding to the top of the logo because in darkmode it looks bad being right next to the top border. I tested this out on PettingZoo (see darkmode here https://pettingzoo.farama.org/main/) and it looks good so I'm mirroring it. Would have preferred a single PR but it's hard to know what mobile will look like before the site is live.
Note: this does not affect any screen sizes above 455px (desktop looks exactly the same)
Note 2:unfortunately I couldn't get the preview with GitHub pages working, but I scaled the text on my browser magnification and screen size until it looked exactly the same as in the phone screenshot, and then adjusted the alignment to look better.
New view:
Previous mobile view:
Fixes # …
=> Fix homepage header text alignment on mobile

gymnasium/envs/mujoco/ant_v4.py
Renamed "links" → "body parts"
renamed "objects" → "body parts"
cleanup obs space description
add excluded elements to the obs table (Not sure if this is desired, review it, if you like it, I will add it to the other MuJoCo Envs)
The main benefit is that it shows the order of observations (in case they are excluded)
=> `Ant` Documentation description and observation cleanup.

gymnasium/vector/vector_env.py
It was:
>>> termination
array([False, False, False])
>>> termination
array([False, False, False])
it is:
>>> termination
array([False, False, False])
>>> truncation
array([False, False, False])
=> Fix typos in the docstrings

gymnasium/experimental/wrappers/rendering.py
Addresses https://github.com/Farama-Foundation/Gymnasium/issues/473 `fps` argument to `RecordVideoV0`
=> Add fps argument to RecordVideoV0

docs/environments/third_party_environments.md
This PR is about adding Gym-Trading-Env to the Thrid Party Environments page.
Over the past weeks, I have been worked on a Trading Gymnasium Environment. This environment is now available though a package named `gym_trading_env`. I made a [documentation available here](https://gym-trading-env.readthedocs.io) with explanations, tutorials, and references.
- Adding a Gym-Trading-Env section in the page "Third-Party Environments" in the "Third-Party Environments" section with : 
- It looks like the environments are sorted by star counts. So I positioned my env according to that right after [Safety-Gymnasium: Ensuring safety in real-world RL scenarios](https://gymnasium.farama.org/environments/third_party_environments/#safety-gymnasium-ensuring-safety-in-real-world-rl-scenarios) :
[![Gymnasium …
=> Add Gym-Trading-Env to Thrid Party Environments

tests/envs/test_compatibility.py
This parametrizes the test `tests/envs/test_compatibility.py::test_shimmy_gym_compatibility` with the parameters `GymV21Environment-v0` and `GymV26Environment-v0`. The latter is skipped if gym < 0.26.0 is installed.
→ For older gym versions the test failed, but it just should not have been tested.
→ not required, the purpose is documented in the reason argument of `pytest.mark.skipif`.
→ not required
→ This fixes (skips) tests if they are not applicable.
=> Test GymV26 compatibility env only for gym>=0.26.0

bin/all-py.Dockerfile, tests/envs/test_rendering.py, tests/envs/utils.py
This PR skips the Mujoco tests in case OpenGL is not available, like in a docker container, see e.g. the section "MuJoCo OpenGL Errors" in [this comment](https://github.com/conda-forge/gymnasium-feedstock/pull/28#issuecomment-1520428770).
When selecting OSMesa by setting the environment variable `MUJOCO_GL=osmesa`, this does not lead to an `ImportError` from Mujoco, but to an `AttributeError` from OpenGL, if OSMesa is not available. This PR adds `AttributeError` to the expected errors, when making the test environments. It triggers a warning, but does not lead to a skipped test. This behavior is analog to the case when EGL is selected, but not available.
Additionally this PR tests if an OffScreenViewer object can be instantiated. It fails when setting the environment variable …
=> Skip Mujoco tests if OpenGL is not available

gymnasium/experimental/wrappers/__init__.py, gymnasium/experimental/wrappers/jax_to_numpy.py, gymnasium/experimental/wrappers/jax_to_torch.py, gymnasium/experimental/wrappers/lambda_action.py, gymnasium/experimental/wrappers/lambda_observation.py, gymnasium/experimental/wrappers/lambda_reward.py, gymnasium/experimental/wrappers/numpy_to_torch.py, gymnasium/experimental/wrappers/stateful_observation.py, gymnasium/experimental/wrappers/stateful_reward.py, gymnasium/experimental/wrappers/vector/__init__.py, gymnasium/experimental/wrappers/vector/dict_info_to_list.py, gymnasium/experimental/wrappers/vector/jax_to_numpy.py, gymnasium/experimental/wrappers/vector/jax_to_torch.py, gymnasium/experimental/wrappers/vector/numpy_to_torch.py, gymnasium/experimental/wrappers/vector/record_episode_statistics.py
Several changes for wrappers from #444 
* Change `lambda_observations.py` to `lambda_observation.py` to follow `lambda_reward.py` and `lambda_action.py`
* Update documentation to follow a common style
* Move `NormalizeObservationV0` to `stateful_observation.py` 
* Move `NormalizeRewardV0` to `stateful_reward.py`
* Rename `VectorListInfo` to `DictInfoToListV0`
* Add vector-based `JaxToNumpyV0`, `JaxToTorchV0`, `NumpyToTorchV0`
* Rename `RecordEpisodeStatisticsV0` from `VectorRecordEpisodeStatistics`
=> Experimental wrapper changes

gymnasium/envs/mujoco/mujoco_env.py
adds a docstring to the `init` of `MujocoEnv`, there has been plenty of confusion on what some arguments do such as `frame_skip` 
=> Add docstring to `MujocoEnv.__init__()`

gymnasium/experimental/vector/async_vector_env.py, gymnasium/vector/async_vector_env.py, gymnasium/wrappers/autoreset.py
The warning in the function's documentation was not rendering properly, so I fixed it.
[AutoResetWrapper](https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.AutoResetWrapper)
| ![스크린샷 2023-05-25 02-44-32](https://github.com/Farama-Foundation/Gymnasium/assets/54899900/973d0fb1-ad89-423c-b7de-13c13d50346e) | ![스크린샷 2023-05-25 02-44-21](https://github.com/Farama-Foundation/Gymnasium/assets/54899900/ce3233a5-6e4a-4298-a4b7-db5140105232) |
[gymnasium.vector.AsyncVectorEnv](https://gymnasium.farama.org/api/vector/#gymnasium.vector.AsyncVectorEnv)
[gymnasium-experimental-vector-asyncvectorenv](https://gymnasium.farama.org/api/experimental/vector/#gymnasium-experimental-vector-asyncvectorenv)
| …
=> Fix comments for correct rendering of warnings

gymnasium/envs/box2d/lunar_lander.py
Observation space of Lunar Lander was altered to solve lander invalid position bug. Current low and high values are (-90, 90) in both x and y dimensions. [Termination condition for lunar lander](https://github.com/Farama-Foundation/Gymnasium/blob/6d103018b48d00f53f264508aac2de14d4123b8d/gymnasium/envs/box2d/lunar_lander.py#LL667C10-L667C10) is currently abs(x) >= 1.0, despite range of (-90, 90). 
There is no termination condition for y position, which explains behavior seen in #377. It is highly unlikely for y to be out of bounds in the current environment due to the large acceptable y value range.
I propose reverting changes to Lunar Lander Observation Space performed in #378,
increasing y-axis bounds to (-2.0, 2.0), and adding failure condition for abs(y)  >= 2.0 to solve behavior seen …
=> Revert Lunar Lander Observation space change

gymnasium/envs/mujoco/mujoco_env.py
Clarifies that `camera_id` and `camera_name` should not be used at the same time
=> fix  `MuJocoEnv.__init__()` camera arguments description.

gymnasium/envs/mujoco/mujoco_env.py, tests/envs/test_custom_mujoco.py, tests/envs/test_mujoco_custom_env.py
For backwards compatibility we keep the old method for asserting `render_fps`.
When `render_fps` is not defined let it be auto defined
useful when using custom `frame_skip` or `xml_file`
=> remove requirement of mujoco envs defining `metadata["render_fps"]`

gymnasium/envs/mujoco/mujoco_env.py, tests/envs/mujoco/test_mujoco_custom_env.py
This adds the  `MujocoEnv._get_reset_info(self)`  which allows the MuJoCo based environments to return `info`
=> [MuJoCo] add the abiltiy for `MujocoEnv.reset()` to return `info`

gymnasium/experimental/wrappers/rendering.py, gymnasium/wrappers/monitoring/video_recorder.py
To replicate the issue, install gymnasium but not moviepy
```python
env = gym.make("CartPole-v1", render_mode="rgb_array")
env = gym.wrappers.RecordVideo(env, "videos")
env.reset()
for _ in range(100):
env.step(env.action_space.sample())
env.close()
```
```
gymnasium.error.DependencyNotInstalled: moviepy is not installed, run `pip install moviepy`
Exception ignored in: <function VideoRecorder.__del__ at 0x7f68807770d0>
Traceback (most recent call last):
File ".../Gymnasium/gymnasium/wrappers/monitoring/video_recorder.py", line 178, in __del__
if not self._closed:
AttributeError: 'VideoRecorder' object has no attribute '_closed'
```
This is partially confusing as the issue is not with `VideoRecorder` but with `_closed`
This PR solves the issue by moving the …
=> Move `import moviepy` such that `__del__` doesn't raise AttributeErrors

gymnasium/experimental/wrappers/common.py, gymnasium/utils/env_checker.py, gymnasium/wrappers/env_checker.py, tests/utils/test_env_checker.py, tests/wrappers/test_passive_env_checker.py
=> Fix broken URL links

gymnasium/experimental/vector/utils/space_utils.py, gymnasium/experimental/wrappers/utils.py, gymnasium/spaces/multi_discrete.py, gymnasium/spaces/utils.py, gymnasium/vector/utils/spaces.py, tests/spaces/test_multidiscrete.py, tests/spaces/test_spaces.py, tests/spaces/test_utils.py, tests/spaces/utils.py, tests/vector/test_shared_memory.py, tests/vector/test_spaces.py, tests/vector/utils.py
Feature addition: `MultiDiscrete` spaces with a starting value, much like `Discrete` spaces. 
No additional dependencies required for this change.
To me it makes more sense to have the `start` argument of the `__init__()` function in second place, however if I did so it would break the code providing `dtype` by position. That's why I put it in the last position, should I change?
=> Adding starting values to MultiDiscrete spaces

gymnasium/envs/registration.py
When users make an environment, if an error is raised then it can be unclear what the env id was or the kwargs, this adds this information to the error.
I choose not to use `raise error("helpful message") from e`, partially due to testing making it more difficult (using pytest) to extract the inner error (`e`).
=> Make the environment creator error more helpful for debugging

docs/tutorials/gymnasium_basics/environment_creation.py
This commit replaces the old documentation for the tutorial, in which Env.step returns a tuple with `done`, with the proper `terminated, truncated`.
Fixes #505
=> docs: update custom env step return :memo:

gymnasium/wrappers/__init__.py, gymnasium/wrappers/rescale_action.py
Describe the bug
Copy and pasted from issue #568 
> The RescaleAction wrapper in (gymnasium.wrappers.rescale_action) does not change the action_space accordingly.
> 
> In contrast, the RescaleAction wrapper in gym.wrappers.rescale_action does!
> 
> When I compare both implementations, the following lines are missing in the gymnasium variant compared to the gym variant.
> 
> self.action_space = spaces.Box(
>     low=min_action,
>     high=max_action,
>     shape=env.action_space.shape,
>     dtype=env.action_space.dtype,
> )
> This looks like a bug to me.
> 
> Code example
> import gymnasium as gym
> #import gym
> 
> env = gym.make("Pendulum-v1")
> env = gym.wrappers.rescale_action.RescaleAction(env, min_action=-1, max_action=1)
> 
> print(env.action_space)
> # gymnasium-->Box(-2.0, 2.0, …
=> Updates the action-space of wrappers.RescaleAction

docs/api/env.md
In the https://gymnasium.farama.org/api/env/#implementing-environments section, it looks like "Env.reset" is missing backticks.
| ![image](https://github.com/Farama-Foundation/Gymnasium/assets/15034841/f7cb51e2-340a-43f6-80fe-752e51d6d560) | _gif/png after_ |
=> docs: fix typo

docs/environments/third_party_environments.md
Since I've added my custom 3rd party environment to the docs, and there's no clear criteria on how to add it to the list, I took the liberty of sorting the pre-existing entries in alphabetical order. Hopefully the order will be respected by future PRs.
I've also removed for those entries the badges' double wrap `[![]()]()`, now it's only `![]()]`. It renders the same and there's no more anchors linking to the "Third-Party Environments" page itself.
=> Alphabetise the third-party environment list

gymnasium/wrappers/monitoring/video_recorder.py, gymnasium/wrappers/record_video.py, tests/wrappers/test_video_recorder.py
I changed the `UserWarning` thrown by `VideoRecorder` into a `ValueError` that gets thrown if `render_mode` is an invalid value. The exception is mirrored inside the constructor of `RecordVideo` so that it fails as soon as possible.
Right now, when you wrap an env in a `RecordVideo`, the code throws only an user warning at the end of the training when it tries to save a video but `render_mode` is set to `None`, or in general to any other value except `rgb_array` and `rgb_array_list`.
It would be nice to check the render mode early, ideally inside the `RecordVideo` constructor, so that the training doesn't have to be restarted in case the parameter was accidentally left unspecified.
| Before …
=> feat: throw error on invalid render mode :technologist:

gymnasium/spaces/multi_discrete.py
Fix a bug in negative value sampling. Reproduce:
```py
>>> s = MultiDiscrete([2, 2], start=[-1, -1])
>>> s.sample()
array([0, 0])
```
The sampling always outputs `-1` values because `np.array([-0.9]).astype(np.int32)` and `np.array([0.9]).astype(np.int32)` both give `array([0], dtype=int32)` i.e., the `astype` methods rounds negative values upwards and positive values upwards. As a result, all values between -1 and 1 exclusive are mapped to 0.
I see 3 options:
1. We can fix it by calling `np.floor` (what I did for now)
2. We can fix it by mapping `x = x-1 if x < 0 else x` over `self.start` at initialization
3. We can replace `self.np_random.random` by `self.np_random.integers`, as it is one for `Discrete` spaces
If one of the other option is better, let me know
=> Fix negative value sampling in MultiDiscrete with non-zero start

.github/workflows/build-publish.yml, .github/workflows/build.yml, .pre-commit-config.yaml, README.md, gymnasium/envs/registration.py, gymnasium/experimental/wrappers/lambda_observation.py, gymnasium/experimental/wrappers/stateful_observation.py, gymnasium/wrappers/compatibility.py, pyproject.toml
`python 3.7` becomes EOL today
so we should drop support for it
=> drop `python 3.7` support

gymnasium/utils/performance.py
Adds `benchmark_step`, `benchmark_init`, `benchmark_render`.
I have used these for development of `MuJoCo-v5`
inspired from: https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/test/performance_benchmark.py
=> Add performance debuging utilities

gymnasium/utils/env_match.py
Adds `info_comparison==keys-equivalence` & `info_comparison==keys-superset` options to `check_environments_match`
motivation: I can use them for a more accurate test for `test_mujoco_v5.py`
=> add `check_environments_match` `info_comparison` options

gymnasium/envs/mujoco/hopper_v4.py
fixes https://github.com/Farama-Foundation/Gymnasium/issues/586
the func is not reached with  `render_mode in ['human', 'rgb_array']`
=> remove Hopper-v4's old render API func

gymnasium/envs/mujoco/assets/hopper.xml, gymnasium/envs/mujoco/assets/walker2d.xml, pyproject.toml
Validation has been made in https://github.com/Kallinteris-Andreas/gym-mjc-v5-model-validation
100mil steps for both models, and they showed identical behavior (on `mujoco==2.3.3`)
Hopper ported by @saran-t (from the mujoco team)
Walker ported by me
Validation by me
=> Update hopper & walker2d with models that do not use local coordinate

pyproject.toml
=> enable `pyright.reportUntypedFunctionDecorator`

bin/all-py.Dockerfile, pyproject.toml
Our CI randomly started to fail, python was released today so we suspect that cython 3 with the introduction on nogail caused the issue
=> Limit cython version on mujoco-py option install

gymnasium/envs/mujoco/mujoco_env.py
Mentions that `v5` is available when `v2` or `v3` are initialized
=> Update `mujoco_py` environment initialization deprecation warning

gymnasium/envs/mujoco/mujoco_rendering.py
Fixed an incorrect use of height in width's place in mujoco_rendering.py
=> Fix mujoco_rendering.py

gymnasium/envs/mujoco/mujoco_env.py, gymnasium/envs/mujoco/mujoco_rendering.py
In debugging I often want to view what's happening with human rendering, but having the window take up a quarter of my screen every time it opened and me needing to resize it with the mouse was frustrating. This change allows (width=, height=) to be passed to gym.make() which will set the human window size properly.
With the way I have currently implemented it the "quarter of screen area" that is currently the default will never be hit because of the defaults on width/height that presently exist. Perhaps we could add a human_width/human_height optionals which will still allow the current default behaviour and then allow customizing with this pull requests changes.
=> Allow changing the size of the viewing window for human rendering

docs/tutorials/training_agents/reinforce_invpend_gym_v26.py
Can we calculate the mean of log probabilities outside the loop and use the `torch.stack` function, to avoid redundant computations and make the update step more efficient? This should improve the performance of the update function and speed up the training process.
=> optimize reinforce_invpend_gym_v26.py

gymnasium/wrappers/stateful_observation.py, gymnasium/wrappers/utils.py, gymnasium/wrappers/vector/__init__.py, gymnasium/wrappers/vector/stateful_observation.py, gymnasium/wrappers/vector/stateful_reward.py, tests/experimental/wrappers/vector/test_normalize_observation.py, tests/experimental/wrappers/vector/test_normalize_reward.py
Continues from https://github.com/Farama-Foundation/Gymnasium/pull/620
Comment on the wrapper:
> The NormalizeReward wrapper normalizes the standard deviation of the discounted returns of every step in an episode.
As we care only about the magnitude of the standard deviation, the wrapper estimates it with the _discounted past rewards_:
$\gamma^{t} * r(0) + ... \gamma * r(t-1) + r(t), \forall t \in [0, T]$
Instead of the discounted return. This has the advantage of updating the std during the rollout without waiting until the end of the episode. 
>
> **Is the magnitude of the std of the _discounted past rewards_ equal to one of discounted returns?**
In general no, but for a good choice of gamma and typical rewards values, yes.
=> ENH: Add NormalizeReward & NormalizeObservation vector wrappers

gymnasium/vector/vector_env.py, tests/vector/test_vector_wrapper.py
As `Wrapper.__getattr__` has been removed to prevent attribute forwarding, we forgot to remove this from `VectorWrapper`, this PR now does this
=> Remove `VectorWrapper.__getattr__`

gymnasium/core.py, gymnasium/vector/vector_env.py, gymnasium/wrappers/stateful_observation.py, gymnasium/wrappers/stateful_reward.py, gymnasium/wrappers/vector/stateful_observation.py, gymnasium/wrappers/vector/stateful_reward.py, tests/wrappers/test_normalize_reward.py, tests/wrappers/vector/test_normalize_observation.py, tests/wrappers/vector/test_normalize_reward.py
We include tests that the `wrappers.vector.NormalizeReward` and `wrappers.vector.NormalizeObservation` wrappers work similarly to `wrappers.NormalizeReward` and `wrappers.NormalizeObservation`. 
However, the bounds on similarity were too small and caused the tests to fail occur. 
As a result, we fix a bug in `wrappers.NormalizeObservation` where every dimension was equally normalize rather than individually normalized. 
For reference, the code used to test and evaluate this
```python
#!/usr/bin/env python
from tqdm import tqdm
import matplotlib.pyplot as plt
from gymnasium.spaces import Box
from tests.testing_env import GenericTestEnv
NUM_ENVS = 3
ENV_ID = "TestEnv-v0"
LENGTH = 500
REPEATS = 100
gym.register("TestEnv-v0", lambda: …
```
=> Improve the normalize vector wrapper tests

docs/tutorials/training_agents/blackjack_tutorial.py
Since the env and agent were defined in the same file, the BlackjackAgent's referencing to 'env' always worked, but technically it wasn't in the scope of the agent.
The same happend with reference to epsilon_decay value which was also initialized in the agents scope.
Specifying the env in the init and get_action functions makes the separation of the classes proper.
=> Fix scoping of variables

docs/environments/third_party_environments.md
Updated the third party env page since CARL is now using gymnasium.
- removed CARL (and also DACBench) from gym list
- added CARL to gymnasium list
Documentation update
=> Update third party environments: CARL to gymnasium

docs/tutorials/training_agents/reinforce_invpend_gym_v26.py
Updated reinforce_invpend_gym_v26.py. This is a simple documentation update that fixes the typo REINFROCE to REINFORCE
=> Documentation update that fixes typo REINFROCE to REINFORCE

gymnasium/__init__.py, gymnasium/core.py, gymnasium/vector/vector_env.py, pyproject.toml, tests/test_core.py
This fixes two bugs
1. The `__getattr__` warning reports the incorrect new function, `get_attr` rather than `get_wrapper_attr`
2. Even when using `get_wrapper_attr`, the warning will be raised due to `get_wrapper_attr` using `hasattr` which under the hood uses `__getattr__`. Therefore, updated to `if name in __dir__()` which should be identical but for simplicities reverted to `hasattr` 
3. Add warning to `VectorEnvWrapper.__getattr__`
=> Fix `__getattr__` warning

gymnasium/wrappers/atari_preprocessing.py, gymnasium/wrappers/jax_to_numpy.py, gymnasium/wrappers/jax_to_torch.py, gymnasium/wrappers/lambda_action.py, gymnasium/wrappers/lambda_observation.py, gymnasium/wrappers/lambda_reward.py, gymnasium/wrappers/numpy_to_torch.py, gymnasium/wrappers/rendering.py, gymnasium/wrappers/stateful_action.py, gymnasium/wrappers/stateful_observation.py, gymnasium/wrappers/stateful_reward.py, pyproject.toml
This adds more example code to the docs for the wrappers.
Todo:
=> Add more examples to docs for wrappers

gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, gymnasium/vector/vector_env.py, gymnasium/wrappers/lambda_observation.py
* Rename `SyncVectorEnv` `observations` to `_observations`, `_terminates` to `_terminations`, `_truncates` to `_truncations`
* Improved the documentation and formatting of `reset` and `step` functions for `AsyncVectorEnv` and `SyncVectorEnv`
* Change return type hint for `AsyncVectorEnv.call` from `list[Any]` to `tuple[Any, ...]`
=> Rename `AsyncVectorEnv` or `SyncVectorEnv` attributes

docs/environments/box2d.md
As discussed in #662 and #677, it appears that swig must be installed separately before the box2d environments can be installed. This PR updates the documentation to reflect this requirement.
Fixes #662
> This is more of a "bug" in the documentation.
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] My changes generate no new warnings
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
=> Add swig to installation instructions for Box2D

.github/workflows/docs-versioning.yml
Added an if statement to the docs versioning workflow that only builds the latest version of the docs if the version name doesn't contain an "a".
=> Avoid alpha versions from being the latest version in the docs

gymnasium/wrappers/vector/vectorize_action.py, gymnasium/wrappers/vector/vectorize_observation.py
=> Fixed `VectorizeTransformAction` and `VectorizeTransformObservation` with different action / obs spaces

gymnasium/wrappers/common.py
* As `autoreset` is no longer an attribute of `EnvSpec`, we need to remove `Autoreset.spec` from when this was true
* Add type hints to `TimeLimit.step` and `TimeLimit.reset`
* Correct the type hints of `RecordEpisodeStatistics` for `time_queue` and use `round` rather than `np.round` since these are scalar values
=> Remove `Autoreset.spec`, add type hints to `TimeLimit`, correct type hint in `RecordEpisodeStatistics`

gymnasium/envs/tabular/cliffwalking.py, gymnasium/envs/toy_text/cliffwalking.py, gymnasium/envs/toy_text/frozen_lake.py
- Corrects Observation Spaces and in particular, player's position calculation from the grid for FrozenLake and CliffWalking's tutorials
- Fixes issue #692 
- **I could not check tests, doctests and build the docs** because of a docker error when trying to build the docker image, and because of architecture problems locally.
> This does not require a documentation update if the documentation is taken from the docstrings.
=> Fixes Frozenlake / Cliffwalking position documentation

gymnasium/spaces/utils.py
The HTML rendering of examples was garbled in this particular API documentation. This change fixes it.
- [v] Bug fix (non-breaking change which fixes an issue)
|![Screenshot 2023-08-30 at 13 11 36](https://github.com/Farama-Foundation/Gymnasium/assets/46875782/b8e4c899-abb2-4db9-9397-39698be84a2e)|![Screenshot 2023-08-30 at 13 11 18](https://github.com/Farama-Foundation/Gymnasium/assets/46875782/9d3f4fe2-585d-4908-a862-a25602b72a9b)|
- [v] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [v] My changes generate no new warnings
=> Fix rendering of examples

docs/README.md, docs/conf.py
This PR aims to solve the following issues:
- building the docs per directions in the ``docs/README.md``, the documentation was built using code of the installed package and thus not necessarily the code in the source tree. This can be confusing for people who have not installed ``gymnasium`` as editable through ``pip install -e .``
- the above is fixed by adding ``.`` and ``..`` in the pathdir in the sphinx ``conf.py``. Due to the executing python statements before the ``import gymnasium``, a ``noqa`` comment was necessary to prevent the linter from rejecting the import.
- the ``autobuild`` command did not work correctly it seems (at least not on my machine) as there were two issues:
1. a build of the documentation creates intermediate ``.pickle`` files in the docs directory, which were …
=> Update documentation build tooling

docs/environments/atari.md
Fix the default value of `frameskip` in the Atari v5 main documentation page. 
This can be quickly checked with:
```python
assert gym.make("ALE/Pong-v5").spec.kwargs["frameskip"] == 4
assert gym.make("ALE/Pong-v5", frameskip=6).spec.kwargs["frameskip"] == 6
```
Fixes #703 
=> Fix frameskip default value (=4) in v5.

gymnasium/spaces/box.py, gymnasium/spaces/multi_discrete.py
Reported an issue with `wrappers.vector.DtypeObservation` which is caused by checking if two observation spaces however the `Box` space doesn't check the `dtype` in its equivalence functions (https://github.com/Farama-Foundation/Gymnasium/issues/705)
This PR updates the `Box` and `MultiDiscrete` spaces to check `dtype`
=> Add dtype check to `Box.__eq__` and `MultiDiscrete.__eq__`

gymnasium/envs/registration.py, tests/envs/registration/test_make.py
If an environment spec has a `max_episode_steps` that is not `None` then there is no way of users to remove the `TimeLimit` wrapper from the environment stack (without setting an extremely high max episode steps limit)
Therefore, this PR adds a special cases to `max_episode_steps` for `0` (`None` was taken as the default value) in order to disable applying the max episode steps parameter. This is very helpful for async or sync vector environments where modifying the environment stack is highly difficult, in particular, async vector env.
=> Add `make(max_episode_steps=0)` to not apply a `TimeLimit` wrapper

gymnasium/envs/mujoco/mujoco_env.py, gymnasium/envs/mujoco/mujoco_rendering.py, tests/envs/mujoco/test_mujoco_rendering.py
Offscreen Renderers do not allow control of viewer dimensions or the maximum number of geometries in the scene. We fix this issue with minimal implementation to address #730. This is motivated by the need to have multiple renderers at different resolutions and to render cluttered scenes
Fixes #730
=> More control over offscreen dimensions and scene geometries

README.md
Change the "it's" to "its", it should be a typo.
- [Yes ] This change requires a documentation update
=> Fixed typo on homepage, "it's" to "its"

docs/environments/mujoco.md
Adds a short description of the available arguments for changing the render properties of `MuJoCo` environments
I am not sure if the main page of MuJoCo is place to place the descriptions, if you have different suggestions of where to put them, i can move them
=> [MuJoCo] add render arguments to the documention

gymnasium/spaces/space.py, pyproject.toml
Bug Fix - addresses a minor syntax issue in the Documentation for the Space class documentation where a Sphinx-style role element was missing the closing `:` character causing documentation rendering errors. 
**While fixing this issue**, it was realized that Pyright was failing with 144 errors in the pre-commit checks all of which were due to a `reportPrivateImportUsage` detection. To address this, an override was added in the `pyproject.toml` file appropriately.
- [X ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [X ] My changes generate no new warnings …
=> Fix for Sphinx role notation in Space Class Documenation

gymnasium/envs/mujoco/assets/swimmer.xml, gymnasium/envs/mujoco/mujoco_rendering.py, pyproject.toml
- **Fix for mujoco rendering**: The `MjData` member `solver_iter` has been renamed to `solver_niter` as specified in the [changelog](https://mujoco.readthedocs.io/en/stable/changelog.html?highlight=solver_niter#general). We are also not using islands in our environments so we just output the first element of the list. Fixes https://github.com/google-deepmind/mujoco/issues/1107
- **Fix for swimmer xml**: As specified in the 11 point of the changelog the `collision` argument has been removed from `option`. 
This PR makes the changes specified in the migration guide. The changelog provides the migration guide for `"pair"` that in the previous mujoco release documentation appears to be named as `"predefined"` such as in the swimmer xml (seems like a release note errata). I haven't compared …
=> [Bug Fix] Small fixes for new mujoco release 3.0.0 

gymnasium/utils/env_match.py
updates `check_environments_match` to also check for that `env.render()` is identical
I have being using it to verify the model changes for the `mujoco==3.0.0`
=> add render check to `check_environments_match` 

tests/wrappers/vector/test_normalize_observation.py
`FAILED tests/wrappers/vector/test_normalize_observation.py::test_against_wrapper` is a reoccurring issue due to the randomness.
This PR fixes the seeds to prevent this issue occurring
=> Fix seeding issue with NormalizeObservation wrapper testing

gymnasium/envs/mujoco/ant_v5.py
=> typo fix in ant_v5 parameter `main_body` type

gymnasium/envs/registration.py, tests/envs/registration/test_register.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/786
=> Fix type for `register(kwargs)`

CITATION.cff, gymnasium/wrappers/jax_to_numpy.py, tests/wrappers/test_jax_to_numpy.py
They caused "missing N required positional argument: 'name', ..." in _iterable_numpy_to_jax or _iterable_jax_to_numpy as the for loop resulted in a generator that NamedTuples could not handle.
NamedTuple is not a useful base class, every used named type needs to be registered individually. jax_to_numpy.register_namedtuple(NewNamedTuple)
[Bug Report] TypeError: <NamedTuple>.__new__() missing 1 required positional argument: '<argument>'
Fixes # (780)
=> Add support for `JaxToNumpy` to handle NamedTuples (fixes #780)

gymnasium/error.py, gymnasium/wrappers/__init__.py
`error.py` contains a number of custom errors for Gymnasium however a number of them are legacy errors that are not used within the project and I doubt a large number of them are used within other projects either, therefore, being removed.
=> Remove unnecessary errors in error.py

docs/environments/third_party_environments.md
the only had expired, you may want to use a different link if you keep some form of statistics, I used the one from the readme
=> fix `third_party_environments.md` `discord` invite link

gymnasium/envs/__init__.py, gymnasium/envs/mujoco/__init__.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/826
=> Stop exporting `MuJoCo-v2` environment bases classes and export `MujocoRenderer`

.github/PULL_REQUEST_TEMPLATE.md
It was just annoying me, that I had to change it every singe time for non-code related changes
or maybe I was supposed to pick "bug fix" all along?
=> add documention [type of change] option in PULL_REQUEST_TEMPLATE.md

gymnasium/envs/__init__.py, gymnasium/envs/phys2d/cartpole.py, gymnasium/envs/phys2d/pendulum.py, gymnasium/envs/tabular/blackjack.py, gymnasium/envs/tabular/cliffwalking.py, gymnasium/functional.py, pyproject.toml
See: https://discord.com/channels/961771112864313344/1029089576398114846/1165900249798287391
This introduces an explicit params object to customize envs within a jitted context. Still sorta WiP, but I want to see full CI
=> Change the functional API to include explicit params

gymnasium/wrappers/stateful_observation.py, tests/wrappers/test_frame_stack_observation.py
FrameStacking as initially (from long time ago) designed filled the buffer with the initial observation from env.reset, I.e. repeated many times as the stacking number.
In the re-implementation the assumption changed to fill it with zeroes, but this not only breaks many codes, it breaks "what is expected" and its proper documentation design.
I have fixed this by using its proper definition:
```
Note:
- After :meth:`reset` is called, the frame buffer will be filled with the initial observation.
I.e. the observation returned by :meth:`reset` will consist of `num_stack` many identical frames.
```
Fixes #829
Also, I have modified the call to super() with self.env as this is the right way for working with wrappers. 
If super() used then unexpected errors can arise when using multiple wrappers. …
=> Add `padding_type` parameter to `FrameSkipObservation` and change default to "reset" to preserve backwards comp

gymnasium/envs/mujoco/mujoco_env.py
Takes a part of the `baseMujocoEnv.__init__()` and factorizes it into its own function
I want to use it in `MJX` and `gymnasium-robotics`
=> refactor `BaseMujocoEnv`'s  `expand_model_path` functionality into its own function

gymnasium/envs/mujoco/ant_v5.py, gymnasium/envs/mujoco/hopper_v5.py, gymnasium/envs/mujoco/humanoid_v5.py, gymnasium/envs/mujoco/walker2d_v5.py
simply removes the single line `terminate` function
https://github.com/Kallinteris-Andreas/gymnasium-changes-validation/tree/main/simplify_termination_code
The environment were validated for 1 mil steps per environment and had identical behavior
performance if less than $\pm 1$ %
=> Factorize `self.terminated` function out in `Ant`. `Hopper`, `Humanoid`, `Walker2d`

docs/index.md, docs/tutorials/third-party-tutorials.md
Follow up to #839 and #866, as an alternative this PR adds a third-party tutorial page for external projects to have a link to their tutorials that incorporate Gymnasium with their project
=> Add third-party tutorial page

gymnasium/utils/env_checker.py
For some environments, they cannot have multiple instances of an environment, e.g. real-world environments.
Therefore, this PR adds an argument that allows disabling testing of the close function within `check_env` 
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/875
=> Add `skip_close_check` to `check_env`

gymnasium/envs/mujoco/mujoco_rendering.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/878
typo fix, remove duplicated line
tested with `mujoco==2.3.7` & `mujoco==3.1.1`
=> Fix MuJoCo human rendering on `mujoco<3`

gymnasium/envs/classic_control/cartpole.py
Currently, `CartPoleVectorEnv.reset()` does not reset the step counter (`CartPoleVectorEnv.steps`). I believe this to be a bug. This PR fixes this issue.
Fixes #885
=> Resetting CartPoleVectorEnv step counter in its reset method

docs/api/wrappers/observation_wrappers.md, docs/api/wrappers/table.md, gymnasium/wrappers/__init__.py, gymnasium/wrappers/transform_observation.py, tests/wrappers/test_add_render_observation.py
`RenderObservation` is an unclear wrapper name, does it mean that the observation is render. 
Therefore, this PR updates the wrapper name to `AddRenderObservation` to make it more clear that the wrapper adds the environment rendering to the environment observation
=> Rename `RenderObservation` wrapper to `AddRenderObservation`

gymnasium/utils/env_match.py, pyproject.toml
makes `check_environments_match` assert fail messages more verbose
=> `env_match.check_environments_match` expand error messages

gymnasium/envs/mujoco/humanoid_v5.py, gymnasium/envs/mujoco/humanoidstandup_v5.py
Fix spelling for Humanoid-v5 and HumanoidStandup-v5 info key
=> Fix "tendon_lenght" to "tenon_length" for Humanoid-v5 info key

docs/environments/mujoco.md, gymnasium/envs/mujoco/mujoco_env.py
This PR simply changes the documentation to explicitly state that `mujoco-py` are deprecated
since this [issue](https://github.com/Farama-Foundation/Gymnasium/issues/921), it is clear that the inclusion of the old MuJoCo environments causes issues to user who do not interact with it
I am not sure about when, the removal of `mujoco-py` environments will happen, probably after 1.0, maybe with the release of `py313`?
=> mark `mujoco-py` environments as explicity deprecated

gymnasium/utils/env_checker.py
Adds an `exact` argument to `utlis.env_checker.data_equivilance` function, which when set to `True` it uses equality comparison of arrays instead of [np.allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html),
testing: this change was manually tested
Note: 
- default behavior does not change,
- We already have a function that has the `exact=True` behavior in `Gymnasium-Robotics`, which can be removed later
https://github.com/Farama-Foundation/Gymnasium-Robotics/blob/main/tests/utils.py#L12-L34
=> add `exact` argument to `utlis.env_checker.data_equivilance`

gymnasium/envs/mujoco/utils.py, tests/envs/mujoco/test_mujoco_v5.py
This was added mainly to address `Gymnasium-Robotics`'s https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/207 https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/208, but it can also be used here and in `metaworld`?
=> Add `check_mujoco_reset_state`

gymnasium/core.py
Fixes a very small typo ("Barton," -> "Barto").
=> fix(docs): typo in `core.py`

gymnasium/spaces/multi_discrete.py
An upstreamed fix for `Multidiscrete.from_jsonable` for the windows os found through the conda gymnasium v0.29.1 (https://github.com/conda-forge/gymnasium-feedstock/pull/32)
=> Fix `Multidiscrete.from_jsonable` for windows

docs/api/spaces.md
A type in the toctree makes the spaces utils link to the vector utils
Fixes #930 
=> Fix docs toctree link (fixes #930)

docs/api/env.md, docs/api/vector.md, docs/api/vector/async_vector_env.md, docs/api/vector/sync_vector_env.md, docs/api/wrappers.md, gymnasium/core.py, gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, gymnasium/vector/vector_env.py, tests/test_core.py, tests/vector/test_vector_env.py
The random seed is fundamentally important for various evaluation protocols. Given the flakyness of RL, one
often wants to evaluate or even train per-seed and then aggregate and present the results with custom logic.
The current design of the environment makes it almost impossible to extract the seed. Numpy's `Generator` object created
by Gymnasium's `np_random` does not expose it, and the seed is not saved anywhere in the env, despite being passed from the user.
This forces users to save seeds somewhere else, which is especially cumbersome when env rollouts are parallelized (which happens all the time).
With this small change we add a hidden attribute `_seed` and a read-only property. It's entirely backwards compatible
Seed of env can't be read out
Please delete options …
=> Made readout of seed possible in env

gymnasium/vector/utils/shared_memory.py, tests/vector/utils/test_shared_memory.py
Soooo shared memory with `Tuple` or `Dict` spaces has been broken since the original implementation (5 years old).
We didn't catch this as the expected tests should be `assert data_equivalence(read_samples, samples)` and were actually just `data_equivalence(...)`. (yes I have checked and can't find anymore instances of this bug in testing)
As a result, the returned samples were roundtripped are
```python
space = Tuple((Discrete(3), Discrete(4)))
num = 2
samples = (space.sample() for _ in range(num))  # ((2, 0), (2, 3))
shared_memory = create_shared_memory(space, n=num, ctx=mp)
for i, sample in enumerate(samples):
write_to_shared_memory(space, i, sample, shared_memory)
read_samples = read_from_shared_memory(space, shared_memory, n=num)  # ((2, 2), (0, 3))
```
This PR fixes the bug
=> Fix reading shared memory for `Tuple` and `Dict` spaces

gymnasium/envs/registration.py, tests/envs/registration/test_make_vec.py
Previously, the `render_mode` passed to vector entry point environments wouldn't work 
```python
envs = gym.make_vec("CartPole-v1", render_mode="rgb_array")
print(envs.render_mode)  # None
```
Therefore, this PR fixes this through disabling `vector_kwargs` for vector entry point environment requiring users to pass parameters with kwargs as is natural with `make`
=> Fix `make_vec(**kwargs)` not being passed to vector entry point envs

docs/conf.py, docs/tutorials/gymnasium_basics/README.rst
Fixes `load_quadruped_model` tutorial not being listed. #902
=> Fix tutorials written in MD not showing

gymnasium/envs/registration.py, gymnasium/utils/env_checker.py, gymnasium/utils/passive_env_checker.py, gymnasium/wrappers/common.py, tests/utils/test_env_checker.py, tests/utils/test_env_checker_with_gym.py, tests/utils/test_passive_env_checker.py, tests/wrappers/test_passive_env_checker.py
I have found several users using a mixture of Gym and gymnasium, I believe due to thinking that 
```python
import gymnasium as gym 
from gym.utils import play
```
will causes the second statement to use gymnasium not gym mistakenly. 
This PR adds more helpful error checking for `check_env`, `make` and the passive environment checker that runs in the background on `make`. 
Tests are included but will be turned off by default as the CI doesn't install gym so `pytest.importorskip` is used if users include `gym` locally
=> Add more helpful error messages if users use a mixture of Gym and Gymnasium

docs/index.md, docs/introduction/basic_usage.md, docs/introduction/migration_guide.md, docs/tutorials/gymnasium_basics/vector_envs_tutorial.py, gymnasium/envs/__init__.py, gymnasium/envs/box2d/lunar_lander.py, gymnasium/wrappers/rendering.py, tests/envs/test_env_implementation.py
This request changes the way `gymnasium/envs/box2d/lunar_lander.py` randomly draws a new `wind_idx` and `torque_idx` so new indexes are drawn randomly whenever the environment is reset rather than only at initialization. This ensures that the environment is statistically independent between episodes, which it is currently not. Changed the version from `v2` to `v3` and added a unit test to check that the seed is correctly working in the new version. 
Fixes #954
=> Randomize LunarLander wind generation at reset to gain statistical independence between episodes

gymnasium/envs/__init__.py
pusher-v2 entry-point was `pucher` not `pusher` meaning that it was not being tested. 
Found through reading the pytest logs
=> Fix pusher-v2 entry-point

gymnasium/envs/mujoco/mujoco_env.py
removes the `_reset_simulation()` to clean up the `MujocoEnv` code
Note: `_reset_simulation()` is not being changed in Robotics or Meta, so it should be an issue 
Validation: the `test/envs/mujoco` is enough
- [Refactor]
=> `MujocoEnv` refactor remove single line function `_reset_simulation()`

gymnasium/envs/mujoco/utils.py
adds the `state_type` argument to `check_mujoco_reset_state` function
motivation: it is useful for testing, as it allows the tester to find which state element is not deterministic on `reset` (currently used to debug an issue in meta)
=> `check_mujoco_reset_state` add `state_type` argument

gymnasium/utils/env_checker.py, tests/utils/test_env_checker.py
fixes https://github.com/Farama-Foundation/Gymnasium/issues/927
=> `env_checker` to use exact data_equivilance

docs/environments/mujoco.md, gymnasium/envs/mujoco/mujoco_env.py, gymnasium/envs/mujoco/mujoco_rendering.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/464
it works with `render_mode="human"` `render_mode="rgb_array"
```py
import gymnasium
import mujoco
import time
from gymnasium.wrappers import HumanRendering, RecordVideo
env = gymnasium.make("Ant-v5", render_mode="human", visual_options={mujoco.mjtVisFlag.mjVIS_CONTACTPOINT: True, mujoco.mjtVisFlag.mjVIS_CONTACTFORCE: True})
env.reset()
for _ in range(1000):
env.step(env.action_space.sample())
env.close()
```
=> [MuJoCo] add `visual_options` rendering argument

gymnasium/envs/mujoco/mujoco_rendering.py, gymnasium/spaces/dict.py, gymnasium/spaces/utils.py, gymnasium/vector/utils/shared_memory.py, gymnasium/vector/utils/space_utils.py, gymnasium/wrappers/utils.py, gymnasium/wrappers/vector/vectorize_observation.py, tests/spaces/test_dict.py
`OrderedDict` were used for legacy reasons when `dict` where no insertion ordered (which `OrderedDict` are).
However, in Python 3.6, python dict were updated for speed and in the process added insertion ordering. 
Therefore, this PR updates the return type of `Dict` space to be a python dict.
However, we probably cannot remove the `self.spaces = sorted(spaces)` as this could break old code that might flatten the dictionary or use `next`, making this bug very difficult to discover
Original issue: https://github.com/Farama-Foundation/Gymnasium/issues/940
=> Remove ordereddict in favour of python dict

gymnasium/envs/box2d/lunar_lander.py
Apply the fix in #728 for Lunar Lander determinism. See #728 for the issue
=> Fix lunar lander determinism

gymnasium/wrappers/stateful_observation.py, tests/wrappers/test_normalize_observation.py
https://github.com/Farama-Foundation/Gymnasium/issues/415 found that when the underlying environment's observation space is not `dtype=np.float64` then when vectorisation, the observation space is incorrect.
This updates this and sets the low / high to `np.inf` as the normalize observation can be anything basically through should settle to mean 0 and std of 1
=> Add NormalizeObservation wrapper observation space

gymnasium/envs/mujoco/utils.py
Previously `set_state` ignored `state_type` argument 
also changed default `state_type` to full physics because it might be needed for third party environments
=> [MuJoCo utils] fix `set_state` 

gymnasium/envs/box2d/lunar_lander.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/752
note: I have not strictly validated that new bounds will never cause it to be out of bounds, but it should at least be extremely rare
```py
import math
env = gym.make('LunarLander-v2')
low = np.array([ -2.5, -2.5, -10.0, -10.0, -2*math.pi, -10.0, -0.0, -0.0, ]).astype(np.float32)
high = np.array( [ 2.5, 2.5, 10.0, 10.0, 2*math.pi, 10.0, 1.0, 1.0, ]).astype(np.float32)
env.unwrapped.observation_space = gym.spaces.Box(low, high)
env.reset()
for _ in range(int(100e6)):
action = env.action_space.sample()
obs, rew, terminated, truncated, info = env.step(action)
assert env.observation_space.contains(obs), obs
if terminated or truncated:
env.reset()
```
=> Fix Lunar Lander Observation space bound

gymnasium/core.py, gymnasium/wrappers/common.py, tests/envs/registration/test_env_spec.py
Fix https://github.com/Farama-Foundation/Gymnasium/issues/555 where using environment kwargs that are unpickleable. 
For each spec that deepcopy that the `env_spec`, the function is surrounded by a try catch
=> Catch exception during `env.spec` if kwarg is unpickleable

gymnasium/envs/registration.py, tests/envs/registration/test_make_vec.py
With `EnvSpec` adding `additional_wrappers`, this was not disabled for `make_vec(..., vectorisation="vector_entry_point")` 
This PR just checks this and raises an error if this is the case
=> Error `make_vec` for vector entry point with non-empty additional wrappers 

gymnasium/spaces/oneof.py, gymnasium/spaces/utils.py, gymnasium/vector/utils/shared_memory.py, tests/envs/mujoco/test_mujoco_v5.py, tests/envs/test_action_dim_check.py, tests/envs/test_envs.py, tests/spaces/test_oneof.py, tests/test_core.py, tests/vector/utils/test_shared_memory.py, tests/wrappers/test_jax_to_torch.py
I noticed that some tests had `return` as a way of stopping a test for various reasons. 
In changing this to `pytest.skip` logging the reason, I found that `OneOf` shared memory actually was broken for various reasons. 
This PR, adds the `pytest.skip` and fixes `OneOf` shared memory by only modifying the sample's subspace memory
=> Fix `OneOf` shared memory and add `pytest.skip` to tests

gymnasium/envs/__init__.py, gymnasium/envs/box2d/bipedal_walker.py, gymnasium/envs/box2d/car_dynamics.py, gymnasium/envs/box2d/car_racing.py, gymnasium/envs/box2d/lunar_lander.py, gymnasium/envs/classic_control/acrobot.py, gymnasium/envs/classic_control/cartpole.py, gymnasium/envs/classic_control/continuous_mountain_car.py, gymnasium/envs/classic_control/mountain_car.py, gymnasium/envs/classic_control/pendulum.py, gymnasium/envs/mujoco/mujoco_env.py, gymnasium/envs/phys2d/cartpole.py, gymnasium/envs/phys2d/pendulum.py, gymnasium/envs/tabular/blackjack.py, gymnasium/envs/tabular/cliffwalking.py, gymnasium/envs/toy_text/blackjack.py, gymnasium/envs/toy_text/cliffwalking.py, gymnasium/envs/toy_text/frozen_lake.py, gymnasium/envs/toy_text/taxi.py, gymnasium/utils/play.py, gymnasium/utils/save_video.py, gymnasium/wrappers/atari_preprocessing.py, gymnasium/wrappers/jax_to_numpy.py, gymnasium/wrappers/jax_to_torch.py, gymnasium/wrappers/numpy_to_torch.py, gymnasium/wrappers/rendering.py, gymnasium/wrappers/transform_observation.py, gymnasium/wrappers/vector/jax_to_numpy.py, pyproject.toml
Inspired by https://github.com/conda-forge/gymnasium-feedstock/pull/36, this PR looks the requirement list again and updates it, adding a `torch` group to mean that users running `pip install gymnasium[other]` doesn't install torch.
Also, updates pip install instructions using groups to use quotes as without it this causes issues for macos users
=> Update requirement list and add quotes around pip install for macos users

gymnasium/envs/mujoco/pusher_v4.py, tests/envs/mujoco/test_mujoco_v5.py
https://github.com/Farama-Foundation/Gymnasium/issues/950 noticed that pusher-v4 had collision issues which was isolated to a bug fixed in mujoco==3.0.0
This collision issue has a major implement on performance, therefore, raising an error for pusher-v4 when mujoco>=3
The issue will be fixed in pusher-v5
=> Raise error for `pusher-v4` environment when `mujoco>=3`

gymnasium/envs/box2d/bipedal_walker.py, gymnasium/envs/box2d/car_dynamics.py, gymnasium/envs/box2d/car_racing.py, gymnasium/envs/box2d/lunar_lander.py
Since the hint for installing swig was already added to the docs in #683 to fix #662 (and many other like #988 #881 #948 #892 #735 #662 ...), I would like to improve the ImportError message.
By replacing the error message from
```python
'Box2D is not installed, run `pip install "gymnasium[box2d]"`'
```
to
```python
'Box2D is not installed, you can install it by run `pip install swig` followed by `pip install "gymnasium[box2d]"`'
```
=> improving ImportError for Box2D

docs/api/vector.md, gymnasium/vector/vector_env.py, tests/vector/test_vector_wrapper.py
Added metadata field to VectorEnv and VectorWrapper. 
Fixes #1005
=> Added metadata field to VectorEnv and VectorWrapper. Implements #1005.

tests/envs/mujoco/test_mujoco_v5.py
Mujoco == 3.1.4 caused the CI to fail due to the updated test. 
In reporting this to mujoco, they say this is just an unreported value 
https://github.com/google-deepmind/mujoco/issues/1589
Therefore, updating for mujoco >= 3.1.4
=> Update `env.model.nbvh` for mujoco>=3.1.4

docs/tutorials/gymnasium_basics/environment_creation.py
Add missing quote to the end of the string in code example.
=> Fix missing closing single quote in environment creation tutorial

gymnasium/envs/mujoco/assets/pusher_v5.xml, gymnasium/envs/mujoco/pusher_v5.py, tests/envs/mujoco/test_mujoco_v5.py
increased the weight of the object to `7.85398163e-06 kg` from `1.30899694e-08 kg` (500x increase)
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/950
testing & validation was done using: https://github.com/Kallinteris-Andreas/Gymnasium-Pusher-v5-model-validation
@Kallinteris-Andreas
and thanks to @HernandezEduin, for initial testing
=> Update Pusher-v5 model to one that is compatible with `mujoco>=3`

gymnasium/envs/registration.py, gymnasium/vector/sync_vector_env.py, tests/envs/registration/test_make_vec.py
When running `gym.make_vec("CartPole-v1", vectorization_mode="sync", max_episode_steps=5)`, this would fail as the `max_episode_steps=5` was passed to the environment kwargs and make kwargs. 
This PR solves the issue by not passing the environment kwargs and only the make kwargs (which include the environment kwargs already)
=> Fix `make_vec` for sync or async and modifying make arguments

gymnasium/envs/registration.py, tests/envs/registration/test_spec.py
While forking the `.envs.registration` module for another project, I noticed that the check in `EnvSpec._check_can_jsonify()` doesn't actually do anything due to a missing `raise`.
Fixes #1030
=> Fix missing `raise`.

gymnasium/wrappers/vector/common.py, tests/wrappers/vector/test_record_episode_statistics.py
Fixed wrappers.vector.RecordEpisodeStatistics episode length computation.
Fixes #1017
=> Fixed `wrappers.vector.RecordEpisodeStatistics` episode length computation from new autoreset api

tests/envs/test_envs.py
Alongside #1033, this PR fixes the reminding `assert data_equivalence` and fixes the pickle tests with minor reordering of the functions
=> Fix pickle env testing

docs/environments/third_party_environments.md
Adding Buffalo-Gym to external environments
Buffalo-gym is a MAB environment and I would appreciate if it was added to the external environments list.
=> Add Buffalo-gym to external environments

docs/tutorials/training_agents/FrozenLake_tuto.py
Small change to the logic in the `docs/tutorial/FrozenLake_tuto.py`, the existing exploitation logic only randomly chooses an action if all actions have the same q-value. Whereas it's possible for a subset of actions to have a maximum q-value.
Updating the logic to retrieve an index of q-values which are equal to the max value, and then randomly selecting an action to take.
=> doc(FrozenLake_tuto): update policy exploitation logic to handle variable sets of maximum Q-values

gymnasium/utils/play.py
Added new option to play which requires the user to provide an input to move the environment forward.  Defaults to False to not break existing implementations.
Fixes #802 
=> Add pause option to play to allow turn based games

gymnasium/spaces/multi_discrete.py, tests/spaces/test_multidiscrete.py
The `__eq__` method in the MultiDiscrete space needs to also check the shape of nvec before the equivalence check. If the shapes are not the same, numpy will throw a ValueError saying operands could not be broadcast together.
The fix here is to simply include a check of the shape before the nvec equivalence check.
Fixes #1044 
I included a handful of tests for checking if MultiDiscrete spaces are equivalent or not. Including a test with different shaped nvecs that would have errored before these changes.
=> Add shape check to MultiDiscrete __eq__ (#1044)

gymnasium/spaces/graph.py
Minor fix to have the proper space in the assertion fail message. Must have been a copy paste error.
=> output edge_space in edge_space assert instead of node_space

.github/workflows/build-publish.yml
Dependant bot is having an issue with one of the upgrades due to us building the project for all the python version.
=> Change publish to only use a single python version

pyproject.toml
With ale-py updated to `>=0.9` to support Gymnasium natively (instead of through shimmy). 
This PR updates the pyproject to reflect this
=> Update Atari install

gymnasium/envs/mujoco/mujoco_py_env.py
Before https://github.com/Farama-Foundation/Gymnasium/pull/934 just running `from gymnasium.envs.mujoco import MuJocoPyEnv` did not resulted in a `error.DependencyNotInstalled` exception, but the expection was only raised when `MuJocoPyEnv.__init__` constructor was called. 
Instead after  https://github.com/Farama-Foundation/Gymnasium/pull/934  just calling `from gymnasium.envs.mujoco.mujoco_py_env import MuJocoPyEnv` results in a `error.DependencyNotInstalled` exception, that I guess create an hard error during test collection.
This result in an hard error when collecting tests in https://github.com/conda-forge/gymnasium-feedstock/pull/36, where `mujoco_py` is not available. Note that there is a similar change in https://github.com/Farama-Foundation/Gymnasium/pull/934 related to `mujoco` …
=> mujoco_py_env: Only raise an exception if MuJocoPyEnv class is actually used

tests/wrappers/vector/test_dict_info_to_list.py
The dtype value of a np.array created from a list of integers is platform dependent, i.e.:
* `np.array([0]).dtype` is `np.int64` on Linux/macOS or
* `np.array([0]).dtype` is `np.int32` on Windows
The `test_dict_info_to_list` hardcodes the expectation that `np.array([0]).dtype` is `np.int64`, this PR fixes this to fix the `test_dict_info_to_list` test on Windows.
=> Fix test_dict_info_to_list test on Windows

gymnasium/wrappers/transform_observation.py
`np.float128` is not available on all platforms (in particular is missing on Windows). This PR uses `np.float128` on the platforms in which it is available, but fallbacks to `np.float64` if `np.float128` is not available.
Fix https://github.com/conda-forge/gymnasium-feedstock/pull/36#issuecomment-2125356983 .
=> Fix RescaleObservation on Windows

gymnasium/core.py, gymnasium/utils/play.py, tests/test_core.py
We previously added `get_wrapper_attr` and `set_wrapper_attr` as recursive wrapper functions to replace `__getattr__`.
However, we did not include `hasattr` equivalent which is helpful as otherwise a try except around a `get_wrapper_attr` is necessary. 
Therefore, this PR added `has_wrapper_attr`
=> Add `has_wrapper_attr`

gymnasium/envs/box2d/lunar_lander.py, gymnasium/wrappers/common.py
Updates the documentation removing old autoreset doc and link to examples agents keyboard_agent only found in lunar lander
=> Remove old autoreset doc and `python examples/agents/keyboard_agent.py` link

gymnasium/wrappers/__init__.py
A small fix to the broken link when clicking on "<ins>the corresponding tutorial</ins>" at the end of [Wrappers section](https://gymnasium.farama.org/api/wrappers/#wrappers). I didn't add an explicit issue for this.
After clicking <ins>the corresponding tutorial</ins> at the end of [Wrappers](https://gymnasium.farama.org/api/wrappers/#wrappers):
| ![before](https://github.com/Farama-Foundation/Gymnasium/assets/56790921/7ec5d256-9ae8-48f4-aa9b-962dbe136455) | ![after](https://github.com/Farama-Foundation/Gymnasium/assets/56790921/38a9ea2c-9280-42ae-b879-6015e91ce5ee) |
=> Fix wrappers tutorial link

.github/workflows/build.yml, bin/all-py.Dockerfile, gymnasium/envs/box2d/car_racing.py, gymnasium/envs/box2d/lunar_lander.py, gymnasium/envs/classic_control/acrobot.py, gymnasium/envs/classic_control/pendulum.py, gymnasium/spaces/dict.py, gymnasium/spaces/discrete.py, gymnasium/spaces/oneof.py, gymnasium/spaces/tuple.py, gymnasium/utils/passive_env_checker.py, gymnasium/wrappers/atari_preprocessing.py, gymnasium/wrappers/stateful_observation.py, gymnasium/wrappers/stateful_reward.py, gymnasium/wrappers/transform_action.py, gymnasium/wrappers/transform_observation.py, gymnasium/wrappers/transform_reward.py, gymnasium/wrappers/vector/dict_info_to_list.py, gymnasium/wrappers/vector/stateful_observation.py, gymnasium/wrappers/vector/stateful_reward.py, gymnasium/wrappers/vector/vectorize_action.py, gymnasium/wrappers/vector/vectorize_observation.py, pyproject.toml, tests/envs/test_action_dim_check.py, tests/spaces/test_spaces.py, tests/utils/test_passive_env_checker.py
Numpy broke some things with the 2.0 release: https://numpy.org/doc/stable/release/2.0.0-notes.html
The tentative policy is that Gymnasium will support both numpy 1.x and 2.x, at least for the foreseeable future. Of course there will be complications everywhere in downstream projects that have other dependencies, but the changes are minor enough that we should be able to handle it here. There will also be minor incompatibilities here, like conflicts with pytorch, and the fact that numpy 2.0 doesn't support python 3.8. Nothing we can do about that.
=> Add compatibility with numpy 2.0

gymnasium/__init__.py
Some environments use PyGame as a default dependency, i.e. they import it on top of environment files instead of when needed as in Gymnasium envs (see for example MiniGrid https://github.com/Farama-Foundation/Minigrid/blob/master/minigrid/minigrid_env.py#L10). For this reason, the env settings for PyGame should be placed before importing the envs.
=> Fix PyGame settings

bin/necessary-py.Dockerfile
It seems that some CI workflows still have a problem with numpy 2.0 due to using a different dockerfile. This should hopefully handle that.
=> Update necessary-py.Dockerfile to pin the numpy version

gymnasium/utils/env_checker.py, tests/testing_env.py, tests/utils/test_env_checker.py
Fixes #1084 (see the issue for the description)
-> No need, already documented
-> No, but catching the non-determinism of `env.reset` was not part of the test, so I let this for further improvement coverage.
You can still check that the new feature works with the code provided in #1084 (the error is now catched by the env checker):
```log
Traceback (most recent call last):
File "/Users/quentingallouedec/Gymnasium/t.py", line 32, in <module>
check_env(gym.make("MyEnv-v0"))  # Passes but:
File "/Users/quentingallouedec/Gymnasium/gymnasium/utils/env_checker.py", line 412, in check_env
check_reset_seed_determinism(env)
File "/Users/quentingallouedec/Gymnasium/gymnasium/utils/env_checker.py", line 116, in check_reset_seed_determinism
assert …
```
=> Check the determinism of `env.reset(seed=42); env.reset()`

gymnasium/wrappers/jax_to_torch.py, gymnasium/wrappers/numpy_to_torch.py
A small fix that propagates the `device` argument when converting from an _Iterable_ of `numpy` or `jax` objects to an _Iterable_ or `torch.Tensor`.
Fixes #1106 
=> Fix non-used device argument in `to_torch` conversion

gymnasium/wrappers/numpy_to_torch.py
A small fix to properly convert `torch.Tenor` into `numpy.ndarray`. As mentioned, converting from `torch` to `jax` does not cause the same error, at least when `jax[cuda]` is installed.
Fixes #1108
=> Fix torch to numpy conversion when on GPU

gymnasium/wrappers/atari_preprocessing.py, tests/wrappers/test_atari_preprocessing.py
Add the option for variable height and widths for the screen size
=> AtariPreprocess - Add an option for tuple[int, int] screen-size

gymnasium/vector/vector_env.py
=> Add missing `NotImplementedError` for `VectorEnv.step` 

gymnasium/logger.py, gymnasium/vector/async_vector_env.py, tests/vector/test_async_vector_env.py
Originally discussed in https://github.com/Farama-Foundation/Gymnasium/issues/182 with reminded in https://github.com/Farama-Foundation/Gymnasium/issues/1114 that the error reporting in `AsyncVectorEnv` is bad as the error occurs in another process. 
To solve this problem, previously the exception type and string were printed however the most important detail is the tracestack.
The problem is that the traceback object can't be passed back
Therefore, this PR converts the traceback to a string that can be passed back which is printed. 
Additionally, testing was added for this feature
=> Add stacktrace reporting to `AsyncVectorEnv`

gymnasium/envs/toy_text/taxi.py
Update the documentation to specify that the starting state is sampled uniformly over 300 states, thus excluding the 100 unreachable states and the 100 states where the passenger is already in the taxi.
Fixes #1115 
N/A
=> Update Taxi environment documentation to clarify starting state definition

gymnasium/envs/classic_control/cartpole.py, gymnasium/wrappers/vector/dict_info_to_list.py, tests/envs/test_env_implementation.py
Recent PRs have failed due to the cartpole env and vector env equivalence failing
I found there were several different reasons that the test failed
1. Non-deterministic - Added `env.action_space.seed(seed=seed)`
2. Episode not over - In the rare case of the episode not terminating or truncating, then the last part of the test doesn't make sense
3. Improved testing - Only a single testing seed was used (randomly selected) making it difficult to assess, this isn't included but testing was completed on 10,000 seeds
4. Updated the cartpole state to be a NumPy array rather than a tuple that ensures that the dtype of variables is constant
5. Update to use NumPy functions rather than `math.cos` etc
=> Fix CartPole for equivalence to vector implementation

gymnasium/envs/functional_jax_env.py, tests/functional/test_func_jax_env.py
See #1122 
FunctionalJaxVectorEnv wasn't adapted to the new autoreset order
=> Fix the off-by-one error in FunctionalJaxVectorEnv

gymnasium/wrappers/stateful_reward.py, gymnasium/wrappers/vector/stateful_reward.py
As discussed in https://discord.com/channels/961771112864313344/1243134869559578675/1270855568336359435
I updated the docstring to reflect the fact that it does not normalize.
=> Update docstring of normalize reward

gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, gymnasium/vector/utils/batched_spaces.py, tests/vector/test_batch_spaces.py, tests/vector/utils/test_space_utils.py
In order to add Meta-World environments to use the Sync/Async Gymnasium methods, a change needed to be made in order to batch observations that have different low/high values.
This change allows the user to specify one of 3 modes for batching observations:
- 'same': current method of having the same observation space for all environments
- 'different': method that allows for different observation spaces to be batched together, given the observation spaces are the same size 
- gym.Space object: allows the user to input a specific method not covered by the 2 above modes
=> Add (A)syncVectorEnv support for sub-envs with different obs spaces

gymnasium/wrappers/common.py, tests/wrappers/test_time_limit.py
- update docstring of `TimeLimit.__init__()`
- add `assert isinstance(max_episode_steps, int) and max_episode_steps > 0`
- I assume `max_episode_steps==0` can be safely disallowed?
- add tests for both assertions
Fixes #1147
=> Fix outdated docs for TimeLimit max_episode_steps and add validation.

docs/environments/third_party_environments.md
Added Tetris Gymnasium environment, based on [this paper](https://easychair.org/publications/preprint/154Q), to the third-party environment documentation.
=> Add Tetris Gymnasium to third party environments

docs/tutorials/gymnasium_basics/implementing_custom_wrappers.py, gymnasium/core.py, gymnasium/envs/functional_jax_env.py
`reward_range` is one of the relics of the wild west approach to API design of Gym. It's not really used ever, it doesn't really have a well defined meaning, so we're removing it from 1.0.
This PR removes it from code (making it a breaking change), and hopefully removes all mentions of it in documentation
=> Remove reward_range

docs/environments/third_party_environments.md
Added the BSK-RL spacecraft tasking RL environment (https://avslab.github.io/bsk_rl/).
Also fixes indentation in the formatting on the external environments page so that bullets work correctly.
=> Add BSK-RL environment; fix indents on bulleted lists

.gitignore
On running Pytest, saved_video* folders are being generated. I have added them to .gitignore.
- It's 88 passed, 4 skipped, 20 warnings
=> Add `save_videos/*` to .gitignore

gymnasium/wrappers/stateful_observation.py, tests/wrappers/test_frame_stack_observation.py
Stack-size of 1 is allowed in Frame Stack Observation Wrapper.
#1085 
=> Allow frame stack size of 1 in FrameStack wrapper

gymnasium/spaces/multi_discrete.py
Removing support for dtype=None but only Integer dtype.
#1195 
=> Check that `MultiDiscrete.dtype` is not None

gymnasium/envs/toy_text/frozen_lake.py
Update the documentation of Frozen Lake environment to include context about the letters in the map
=> Update frozen_lake.py documentation

docs/conf.py
The copyright date is out of date in the documentation, this fixes it
=> set copyright time in documentation page automatically

gymnasium/wrappers/numpy_to_torch.py
Replaces all the leftover "Jax" with "NumPy" and makes capitalization of NumPy uniform within the file.
=> documentation: replace "Jax" with "NumPy" and make capitalization uniform

.pre-commit-config.yaml, pyproject.toml
=> update pyright to 1.1.383

gymnasium/envs/box2d/lunar_lander.py, pyproject.toml
`reportPrivateImportUsage` was due to MuJoCo, but this has been fixed in (a while ago) v5
`reportUnboundVariable` I have no idea when this was an issue
also cleans up options in `pyproject.toml`
=> re-enable `pyright.reportPrivateImportUsage` and `pyright.reportUnboundVariable`

tests/envs/registration/test_make_vec.py
On Windows, I was obtaining these test failures:
~~~
2024-10-20T14:32:51.8042643Z FAILED tests/envs/registration/test_make_vec.py::test_async_with_dynamically_registered_env[fork] - ValueError: cannot find context for 'fork'
2024-10-20T14:32:51.8043645Z FAILED tests/envs/registration/test_make_vec.py::test_async_with_dynamically_registered_env[forkserver] - ValueError: cannot find context for 'forkserver'
~~~
This is happening as `fork` and `forkserver` are not supported on Windows, and other platforms may have similar limitations. To avoid such test failures, I modified the `test_async_with_dynamically_registered_env` parametrization to use [`multiprocessing.get_all_start_methods()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_all_start_methods) instead of …
=> Use multiprocessing.get_all_start_methods() in test_async_with_dynamically_registered_env

bin/all-py.Dockerfile, bin/necessary-py.Dockerfile
Building the docker container now takes ~1min40, was 2min40 before.
=> Add uv to install pip deps in workflows

gymnasium/envs/mujoco/mujoco_rendering.py
The width and height of OffScreenViewer cannot be None otherwise, it will cause the error. Adding a type check before creating the opengl_context could provide more information for debugging.
Fixes #1225
=> Add width and height check for MujocoRenderer

docs/environments/third_party_environments.md
Contribute third_party_environments.md, add links to Itomori, a custom gymnasium environment used to explore UAV agents in a risky environment, used to do research on chance constrained MDPs.
No additional dependencies needed.
(Not applicable(?) - it's just changes to the md file.)
If there's anything I need to run, please let me know.
=> Add Itomori custom env to third_party_environments.md

.gitignore, docs/introduction/train_agent.md, docs/tutorials/training_agents/blackjack_tutorial.py, pyproject.toml
There is something off in the blackjack tutorial code. The current version uses a `deque_size` parameter which doesn't  exist. I renamed it `buffer_length`, hoping this is the right parameter to use.
In order to test my code, I had to add a missing dependency (seaborn) to `pyproject.toml`.
I also gitignored the `/.venv` subfolder, which I think is quite frequently used for storing virtual envs.
=> Fix parameter name in tutorial code

docs/introduction/create_custom_env.md
=> Confusing wording in create_custom_env.md

gymnasium/envs/toy_text/blackjack.py
This PR fixes a comment in line 62 in gymnasium/envs/toy_text/blackjack.py. The comment should say `- Numerical cards (2-10) have a value equal to their number.` instead of `- Numerical cards (2-9) have a value equal to their number.`
Fixes #1249
=> fixed typo in gymnasium/envs/toy_text/blackjack.py, 2-10 instead of 2-9

gymnasium/envs/box2d/car_racing.py, tests/envs/test_env_implementation.py
CarRacing-v3 in discrete mode first converts the action to a float value before checking if the action is part of the discrete action-space. This causes an error to be raised.
Minimal example to reproduce this error:
```
env = gym.make("CarRacing-v3", continuous=False)
_ = env.reset()
action = env.action_space.sample()
_ = env.step(action)
```
This problem can be fixed simply by moving the float conversion to after the `if self.continuous:` check such that for the discrete case `else:` the action will still be an integer. And the `InvalidAction` error is not raised.
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have added …
=> Fix discrete CarRacing-v3

docs/introduction/train_agent.md
The convolution added in https://github.com/Farama-Foundation/Gymnasium/pull/1237/commits/28d50ce5fe99ce9d23e30ae7aa80e7a457ab7d0a doesn't average over 100 frames but sums them instead.
=> Fix scaling in plots

docs/tutorials/training_agents/blackjack_tutorial.py
Looks like the API for RecordEpisodeStatistics changed at some point. Quick one-liner to get this working.
I tried running the tutorial and it didn't work without this change. Looks like it was out of date. Quick one-liner to get this tutorial working by using the update API for RecordEpisodeStatistics. 
https://github.com/openai/gym/blob/dcd185843a62953e27c2d54dc8c2d647d604b635/gym/wrappers/record_episode_statistics.py#L84C29-L84C29
=> Fix RecordEpisodeStatistics param in Blackjack Tutorial (one line)

gymnasium/envs/classic_control/cartpole.py, gymnasium/envs/functional_jax_env.py, gymnasium/envs/phys2d/cartpole.py, gymnasium/envs/phys2d/pendulum.py, gymnasium/envs/registration.py, gymnasium/envs/tabular/blackjack.py, gymnasium/envs/tabular/cliffwalking.py, gymnasium/vector/__init__.py, gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, gymnasium/vector/vector_env.py, gymnasium/wrappers/vector/common.py, gymnasium/wrappers/vector/stateful_observation.py, gymnasium/wrappers/vector/vectorize_observation.py, pyproject.toml, tests/envs/registration/test_make_vec.py, tests/testing_env.py, tests/vector/test_autoreset_mode.py, tests/vector/test_vector_env.py, tests/vector/test_vector_env_info.py, tests/wrappers/vector/test_vector_wrappers.py
With the change in Gymnasium v1.0, some users have requested support for the other vector autoreset APIs / modes:
1. Next step - This is the default API. When a sub-environment terminates or truncates, its reset function is called in the next step. 
2. Same step - This is <1.0 API, on a sub-environment terminating or truncating; within this step, the sub-environment will call reset. The resulting terminating / truncating observation is stored in `info["final_obs"]` with the reset observation passed back to the step's `obs`. 
3. Partial reset / disabled autoreset - Some users wish to disable autoreset and partially reset the environment themselves. Though unadvised, partial resets can be used with the prior two APIs. This API will not autoreset on a termination or truncation signal. …
=> Add support for different vector autoreset modes

gymnasium/envs/mujoco/mujoco_rendering.py
Fixes #1261 as #1229 accidentally moved the `rgb_img = rgb_img[::-1, :, :]` to only be run when `segmentation` is True.
=> Fix Mujoco Rendering for `rgb_array` that is upside down

docs/introduction/record_agent.md
Fix typo in documentation.
This corrects RecordEpisodicStatistics to RecordEpisodeStatistics in the documentation.
- [ x] Documentation only change (no code changed)
=> Fix typo in documentation

docs/environments/third_party_environments.md
Add BlueSky-Gym, a collection of air traffic management environments to the third party environments ([https://github.com/TUDelft-CNS-ATM/bluesky-gym](url)).
Unsure where it would fit best, placed in 'Autonomous Driving environments' because it belongs to the sub-category autonomous vehicle and traffic management.
=> Added BlueSky-Gym to third party envs

docs/environments/third_party_environments.md
Initial PR #1276 by did not have appropriate spacing in the .md file, causing the gymnasium version dependencies to be displayed in line:
With this PR the file is changed to ensure appropriate spacing, consistent with the other environments:
Apologies for not catching this in the first PR
=> fixed incorrect spacing BlueSky-Gym third_party_environments.md file

gymnasium/envs/mujoco/mujoco_rendering.py
A detailed comment is provided in my name under the issue referenced. 
The change summary is:
- Added `AttributeError` exception handling to the `free()` method in `mujoco_rendering.py`.
- Gracefully handles freeing the OpenGL context and closing the GLFW window in the event that the user does not call `env.close()` before the program terminates when they've set `render_mode: 'human'`.
- Added docstring for the `free()` method.
Fixes  #1224
=> Add error message when terminating the MuJoCo renderer without calling `env.close`

.pre-commit-config.yaml, gymnasium/wrappers/stateful_observation.py, tests/wrappers/test_time_aware_observation.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/1282 that adds support to the `TimeAwareObservation` wrapper for environments without a `spec`
Adds tests to check that this works
=> Add `TimeAwareObservation` support for environments without a `spec`

gymnasium/spaces/dict.py, tests/spaces/test_dict.py
Fixes https://github.com/Farama-Foundation/Gymnasium/issues/1290 reverting `Dict` space key ordering from [this](https://github.com/Farama-Foundation/Gymnasium/blame/a79e5d6e8a41885245bea481e36746539ecbf872/gymnasium/spaces/dict.py#L70) and was removed in https://github.com/Farama-Foundation/Gymnasium/pull/977
=> Revert `OrderedDict` key ordering in `Dict` space

gymnasium/wrappers/vector/vectorize_action.py, gymnasium/wrappers/vector/vectorize_observation.py, tests/wrappers/vector/test_transform_action.py, tests/wrappers/vector/test_transform_observation.py
=> Add `wrappers.vector.TransformObs/Action` single obs/action space argument

gymnasium/wrappers/stateful_reward.py, gymnasium/wrappers/vector/stateful_reward.py
Changes the documentation of reward scaling wrappers. It mainly removes incorrect or unsubstantiated information.
Affected wrappers are [wrappers/stateful_reward.py](https://github.com/Farama-Foundation/Gymnasium/blob/c11ac0501594fb2b5bf3b932698f2b4085bf7414/gymnasium/wrappers/stateful_reward.py) and [wrappers/vector/stateful_reward.py](https://github.com/Farama-Foundation/Gymnasium/blob/c11ac0501594fb2b5bf3b932698f2b4085bf7414/gymnasium/wrappers/vector/stateful_reward.py).
Fixes #1272 
=> Update documentation for reward scaling wrappers

gymnasium/core.py, tests/test_core.py
IMHO, the current implementation of `get_wrapper_attr` and `set_wrapper_attr` is flawed because they act inconsistently wrt each other. For instance, these two snippets is failing:
```python
env = gym.make("CartPole-v1")
env.MY_ATTRIBUTE = True
assert env.get_wrapper_attr("MY_ATTRIBUTE")
env.set_wrapper_attr("MY_ATTRIBUTE", False)
assert not env.get_wrapper_attr("MY_ATTRIBUTE")
```
```python
env = gym.make("CartPole-v1")
env.set_wrapper_attr("MY_ATTRIBUTE", False)
assert hasattr(env, "MY_ATTRIBUTE")
```
First, I think that if the top-most wrapper has the attribute, `set_wrapper_attr` should set it (by the way, this is what the documentation is stating). When it does not, then it is not clear whether it should raise an exception (basically …
=> Fix `get_wrapper_attr` / `set_wrapper_attr`.

gymnasium/envs/toy_text/cliffwalking.py
Environment `CliffWalking-v0` with human rendering enabled is not calling `pygame.quit()` when closing. This causes the rendered pygame window to stick until `pygame.quit()` is called manually.
This PR implements the missing method `close()` similarly as in other `toy_text` environments.
I believe the missing items from the Checklist are not necessary for this bugfix.
=> Quit Pygame when cliffwalking environment is closed

.github/workflows/run-pytest.yml, gymnasium/wrappers/jax_to_torch.py, pyproject.toml, tests/wrappers/test_jax_to_torch.py
This PR adds support for the modern dlpack API to transfer jax arrays to torch tensors and vice-versa. We now determine at initialization if the installed versions of jax and pytorch meet the API requirements, and select the suitable conversion path based on that flag.
Fixes #1298
=> Add full support for dlpack API

gymnasium/envs/classic_control/continuous_mountain_car.py
The `MountainCarContinuous` documentation states that the observation space is unbounded (`-inf` to `inf`) for both dimensions - this is not the case. This PR updates the documentation to reflect the actual bounds of the observation space.
=> Fix MountainCarContinuous documentation

gymnasium/envs/registration.py
In `make_vec`, `env_spec_kwargs` is first stripped of all arguments which do not belong to the underlying environment (`num_envs`, `vectorization_mode`, ...). Then `create_single_env` is defined, where `env_spec_kwargs` is used to create the environment, which is then passed to either `SyncVectorEnv` or `AsyncVectorEnv`. After those vector environments are created, the stripped arguments are added to `env_spec_kwargs` again.
`AsyncVectorEnv` keeps a reference to `create_single_env` in a publicly accessible field `AsyncVectorEnv.env_fns`. The problem is now that because the stripped arguments were added to `env_spec_kwargs` again, `create_single_env` does not work anymore, as it will now try to pass arguments such as `num_envs` to the environment constructor. 
In my workflow, I need to …
=> Prevented accidental alteration of env_spec_kwargs in make_vec

gymnasium/wrappers/jax_to_numpy.py, gymnasium/wrappers/jax_to_torch.py, gymnasium/wrappers/numpy_to_torch.py, tests/wrappers/test_jax_to_numpy.py, tests/wrappers/test_jax_to_torch.py, tests/wrappers/test_numpy_to_torch.py
The `JaxToNumpy`, `JaxToTorch` and `NumpyToTorch` wrappers currently have no conversion registered for `None` values. This becomes an issue e.g. when calling `env.render()` in "human" render modes, which implicitly returns `None`. Consider the following code:
```python
from gymnasium.wrappers.jax_to_numpy import JaxToNumpy
from tests.testing_env import GenericTestEnv
jax_env = GenericTestEnv()
numpy_env = JaxToNumpy(jax_env)
numpy_env.render()
```
The snippet fails because there is no None type conversion between NumPy, torch and jax. This PR fixes the behavior for all conversion wrappers and adds appropriate tests. The direct propagation of `None` is reasonable because its meaning does not change across the frameworks.
=> Add None to None conversion for JaxToNumpy, JaxToTorch and NumpyToTorch

gymnasium/core.py
I propose to further improve 'set_wrapper_attr' (as a follow-up of PR https://github.com/Farama-Foundation/Gymnasium/pull/1293). 
I added the optional keyword argument 'force'. Its role is to make sure that the attribute exists before setting it, so that no attribute while be create on the top-level wrapper. While this could already be done using 'has_wrapper_attr', but specifying the new optional argument is not only more convenient but also faster. Moreover, adding this extra argument enables to refactor the implementation of 'set_wrapper_attr' as a recursive function calling itself on the lower-level environment (in case of wrappers). This is not only more than twice faster (because `isinstance` is very slow...), but also more robust, as __it allows anybody to derive its own wrapper …
=> Improve 'set_wrapper_attr'.

gymnasium/wrappers/atari_preprocessing.py, tests/wrappers/test_atari_preprocessing.py
Fix observation shape of `AtariPreprocessing` when the screen is not square. Since screen size are directly passed into `cv2.resize`, its order should be width x height. Observation shape should be `height x width`.
https://github.com/Farama-Foundation/Gymnasium/blob/a4f8cfbcd8a350d5d11aa920adb9c220bd716d32/gymnasium/wrappers/atari_preprocessing.py#L219-L223
=> Allow `AtariPreprocessing` non-square observations

docs/requirements.txt, gymnasium/spaces/box.py, gymnasium/spaces/dict.py, gymnasium/spaces/discrete.py, gymnasium/spaces/graph.py, gymnasium/spaces/multi_binary.py, gymnasium/spaces/multi_discrete.py, gymnasium/spaces/oneof.py, gymnasium/spaces/sequence.py, gymnasium/spaces/space.py, gymnasium/spaces/text.py, gymnasium/spaces/tuple.py, tests/spaces/test_box.py, tests/spaces/test_dict.py, tests/spaces/test_discrete.py, tests/spaces/test_graph.py, tests/spaces/test_multibinary.py, tests/spaces/test_multidiscrete.py, tests/spaces/test_oneof.py, tests/spaces/test_sequence.py, tests/spaces/test_text.py, tests/spaces/test_tuple.py
Adds a probability mask feature (`probability`) to the `sample()` method of all spaces. This allows you to specify the probability of choosing each action. Similarly to the `mask` parameter, the `probability` parameter is a numpy array with the same shape as `n`, the number of elements in the space. Each value in the array describes the probability of the corresponding value being chosen, with 0 meaning it will not be chosen and 1 meaning that it will be chosen. All of the values in the array must sum to 1. `probability` is unsupported for the Box space.
This is helpful in instances where values need to be chosen at random, such that some values are given higher priority (a higher likelihood) over others. For example, when implementing an Ant Colony Optimization algorithm, each action …
=> Add probability masking to `space.sample`

gymnasium/wrappers/vector/numpy_to_torch.py
It seems that the vector `NumpyToTorch` class was created from `JaxToTorch`, so some misleading artifacts referring to JAX instead of NumPy still exist in the documentation and variable names.
Fixed:
- `jax_action` -> `numpy_action` variable name
- `Jax-based` + `jax arrays` -> `NumPy-based` + `NumPy arrays` in the docs
I apologize that I haven't tested the changes — just made a quick fix via web github editor.
_PS. Thank you guys for your great job!_
=> Refer to numpy instead of jax [for vars and docs] in vector NumpyToTorch

gymnasium/envs/mujoco/mujoco_env.py, tests/envs/mujoco/test_mujoco_rendering.py
Fixes https://github.com/Farama-Foundation/Gymnasium-Robotics/issues/265 through removing the assertation check and moving the assertion into the tests
=> Remove Mujoco assert on metadata render-mode

gymnasium/envs/classic_control/continuous_mountain_car.py
This PR fixes two typos in the documentation of the continuous mountain-car environment.
It can be seen in the discrete version (and is common sense) that the dynamics of $v_{t+1}$ should not mention $v_{t+1}$.
https://github.com/Farama-Foundation/Gymnasium/blob/3287c869f9a48d99454306b0d4b4ec537f0f35e3/gymnasium/envs/classic_control/mountain_car.py#L60
=> Fix typos in continuous mountain-car documentation

gymnasium/envs/mujoco/mujoco_rendering.py, pyproject.toml, tests/envs/mujoco/test_mujoco_rendering.py
This PR fixes the `add_markers` function for mujoco's `BaseRender`. The API had a breaking change in between 3.1.x and 3.2. We now check the mujoco version on import and set a feature flag that switches between legacy behaviour and new (standard) behaviour.
Fixes #1326
This fix adds `packaging` as dependency. This is required to compare against all possible versions that comply with [PEP 440](https://peps.python.org/pep-0440/).
>**Note:** It also bumps the required mujoco version to 2.3.6. Prior versions fail all unit tests because gymnasium uses type annotations that did not exist prior to 2.3.6.
>**WARNING:** The test suite still fails for `tests/envs/mujoco/test_mujoco_v5.py::test_model_object_count[v5]` with mujoco<3.1.4. To get all tests …
=> Fix MuJoCo add_markers for mujoco>=3.2

gymnasium/wrappers/__init__.py, gymnasium/wrappers/rendering.py, tests/wrappers/test_white_noise_rendering.py
Added two wrappers that add white noise to the rendering of the environments. 
The first simply randomly add white noise to every pixel according to some probability. 
The second adds biggers "patches" (the number of patches depends on the size of the patch and on what percentage of pixels we want to mask). 
Noise is different at every step. 
This is not a fix, but a new feature. It allows for noisy pixel observations and can easily make the environment partially-observable (especially the "patch" version). Helpful to turn MDPs into POMDPs from pixels. 
The reasons why I added it as a rendering wrapper and not an observation wrapper are:
1. It can be used with both RGB and grayscale rendering,
2. It can be used with other observation wrappers (e.g., both dictionary with both pixels and …
=> Add rendering wrapper with noise

docs/environments/mujoco.md
Quadruped was misspelled as 'Quarduped' within the MuJoCo documentation. This change just swaps two letters. No change in functionality.
=> Fixed misspelling of 'Quadruped' within MuJoCo documentation.

gymnasium/envs/__init__.py
Update toytext.CliffWalking env version in envs registry,
Motivation:
the example included in the documentation is not working.
https://gymnasium.farama.org/environments/toy_text/cliff_walking/
```python
gym.make('CliffWalking-v1')
```
=> Update toytext.CliffWalking env version in envs registry

.github/workflows/run-tutorial.yml
For the main project we have a large amount of testing in `tests` that will run for every PR to ensure that bugs are catch. 
However, for the documentation, we don't have such automated testing. 
This PR addes testing for all the tutorials to ensure that they still work as expected. 
These tests are only run in PRs on tutorials that are modified (to ensure quick responses) and for all tutorials once merged to check if any unintended changes were made.
=> Add CI for testing tutorial implementations

.github/workflows/run-tutorial.yml
In cases, where one of the tutorials is updated / changed then the other tutorials are not run which means that `total` and `failed` are not initialised causing issues, for example in https://github.com/Farama-Foundation/Gymnasium/pull/1345
This PR fixes it but initialising the variables as 0 if not defined
=> Fix `run-tutorial.yml` in edge case

gymnasium/envs/box2d/car_racing.py
The description of the continuous argument in the car_racing environment states:
```
`continuous=True` converts the environment to use discrete action space.
```
However, this is incorrect. Setting `continuous=True` actually enables a continuous action space, not a discrete one. This PR corrects the misleading comment.
=> fix documentation of car-racing continuous argument

gymnasium/wrappers/jax_to_numpy.py, gymnasium/wrappers/jax_to_torch.py
The recently release `jax` 0.6.0 (https://github.com/jax-ml/jax/releases/tag/jax-v0.6.0), impacts the dispatch behavior of `jax_to_numpy`.
When called with an argument of type `<class 'jaxlib.xla_extension.ArrayImpl'>`, the `_iterable_jax_to_numpy` is called.
It crashes with:
```
>           return type(value)(jax_to_numpy(v) for v in value)
E           TypeError: (): incompatible function arguments. The following argument types are supported:
E               1. (self, aval: object, sharding: object, arrays: list, committed: bool, _skip_checks: bool = False) -> None
E
E           Invoked with types: jaxlib.xla_extension.ArrayImpl, generator
gymnasium/wrappers/jax_to_numpy.py:112: TypeError
```
Before, the `_device_array_jax_to_numpy` was called instead.
This patch adds a special case for …
=> Fix jax 0.6.0 regression in jax_to_numpy

gymnasium/envs/box2d/car_racing.py
This PR modifies the docstring for the discrete action descriptions (steer right, steer left) and also updates an in-line comment for consistency in `gymnasium/envs/box2d/car_racing.py`.
Fixes #1369
=> Fix CarRacing discrete action docstring

docs/introduction/speed_up_env.md
Fixed Typo on speed_up_env.md. The typo was changed from "Academic Researchers are consistently explore" to "Academic Researchers are consistently exploring"
Fixes #1374 
=> Fixed Typo on speed_up_env.md

.github/workflows/docs-build-dev.yml, .github/workflows/docs-build-release.yml, .github/workflows/docs-manual-build.yml, .github/workflows/run-pytest.yml, .github/workflows/run-tutorial.yml, README.md, docs/api/wrappers/misc_wrappers.md, docs/api/wrappers/table.md, gymnasium/wrappers/array_conversion.py, gymnasium/wrappers/jax_to_numpy.py, gymnasium/wrappers/jax_to_torch.py, gymnasium/wrappers/numpy_to_torch.py, gymnasium/wrappers/vector/array_conversion.py, gymnasium/wrappers/vector/jax_to_numpy.py, gymnasium/wrappers/vector/jax_to_torch.py, gymnasium/wrappers/vector/numpy_to_torch.py, pyproject.toml, tests/testing_env.py, tests/wrappers/test_array_conversion.py, tests/wrappers/test_jax_to_numpy.py, tests/wrappers/test_jax_to_torch.py, tests/wrappers/test_numpy_to_torch.py, tests/wrappers/vector/test_array_conversion.py
Recently, environments implemented in frameworks such as `torch` and `jax` have gained importance as they provide a convenient way to run parallelized environments on GPUs and compile parts of the logic. To enable the mixing of environments written in one framework and training in another framework, `gymnasium` provides wrappers that automatically convert from one framework to the other and back. However, only a few combinations are currently implemented, namely [JaxToNumpy](https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.JaxToNumpy), [JaxToTorch](https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.JaxToTorch) and [NumpyToTorch](https://gymnasium.farama.org/api/wrappers/misc_wrappers/#gymnasium.wrappers.NumpyToTorch). Other combinations, …
=> Add generic conversion wrapper between Array API compatible frameworks

docs/introduction/basic_usage.md
Fixed broken links on the Basic Usage page that were previously leading to 404 errors.
=> Fix broken links on the Basic Usage page

gymnasium/envs/mujoco/mujoco_py_env.py, gymnasium/spaces/space.py, gymnasium/spaces/utils.py, gymnasium/utils/play.py, gymnasium/vector/async_vector_env.py, gymnasium/vector/utils/shared_memory.py, pyproject.toml
Reenables the `reportInvalidTypeForm` pyright rule.
Since `mujoco_py_env.py` is no longer being maintained, I chose to silence all typing errors from the file instead of fixing the type annotation (on L322).
=> Reenable `reportInvalidTypeForm` typing rule

gymnasium/__init__.py
This pull request is directly linked to the proposal of the same name, which is to stop overriding the SDL audio driver on Linux. See the proposal for more details as well as the related motivations.
Fixes #1386 (issue)
N/A
=> Don't override SDL's audio driver on Linux

gymnasium/wrappers/atari_preprocessing.py
Testing AtariPreprocessing with all environments, then Video Checkers and Backgammon which don't have NOOP actions raise an assertion error for `assert env.unwrapped.get_action_meanings()[0] == "NOOP"`
This PR only triggers this assertion if `noop_max` is greater than 0
=> Atari Preprocessing - Only check env has NOOP action when `noop_max>0`

tests/wrappers/test_array_conversion.py
The roundtrip test for `ArrayConversion` fails for `array-api-strict` if installed because of an unintentional use of `array.all()` instead of `xp.all(array)` in the test code itself. This PR fixes the test for array-api-strict.
=> Fix roundtrip test for ArrayConversion

gymnasium/vector/async_vector_env.py, gymnasium/vector/sync_vector_env.py, tests/vector/test_vector_env.py
Added action space assertion in `AsyncVectorEnv` `step` method to ensure that the actions passed to the step method are validated against the action space, preventing `step_await` hangs forever.
Fixes #1417 
=> [Bugfix] fixed `step()` function in `AsyncVectorEnv` from hanging forever

gymnasium/envs/mujoco/mujoco_rendering.py, tests/envs/mujoco/test_mujoco_rendering.py
The current MuJoCo `WindowViewer` clears markers after each `render` calls, but the `OffscreenViewer` does not. This leads to unexpected behavior when continuously adding markers to the scene: The `human` render mode works as expected but `rgb_array` raises a MuJoCo error that the maximum number of geoms has been exceeded. This PR makes the behavior consistent across viewers and tests that markers are cleared after each render call.
Clear markers after rendering for MuJoCo OffscreenViewers
=> Clear markers after rendering for MuJoCo OffscreenViewers

gymnasium/envs/tabular/blackjack.py
⏱️ Runtime :   **`104 milliseconds`**  **→** **`8.75 milliseconds`** (best of `33` runs)
The optimized code achieves an 1088% speedup through two key JAX-specific optimizations:
**1. JIT Compilation (@jax.jit decorators)**
- Added `@jax.jit` to both `usable_ace()` and `sum_hand()` functions
- JIT compilation transforms these functions into optimized XLA kernels that run much faster than Python interpretation
- Eliminates Python function call overhead and enables aggressive compiler optimizations
**2. Vectorized JAX Operations**
- Replaced `jnp.count_nonzero(hand == 1) > 0` with `jnp.any(hand == 1)` - more direct and efficient for checking existence
- Replaced Python's `sum(hand)` with `jnp.sum(hand)` - keeps computation entirely within JAX's accelerated framework
- Eliminated mixed …
=> Optimise the `BlackjackFunctional` `usable_ace` and `sum_hand` functions

gymnasium/wrappers/array_conversion.py
The array conversion from numpy environments to torch cuda observations currently fails because torch has not yet implemented full support for dlpack. This PR fixes the conversion. The issue can easily be reproduced by running the following snippet:
```python
import torch
from gymnasium.wrappers import ArrayConversion
env = gym.make("Pendulum-v1")
env = ArrayConversion(env, env_xp=np, target_xp=torch, target_device="cuda")
obs, info = env.reset()
action = torch.tensor(env.action_space.sample()).cuda()
next_obs, reward, terminated, truncated, info = env.step(action)
```
We currently do not run GPU tests, hence it is not possible to add testing.
=> Fix array-conversion for torch cuda tensors
